README.rst

when I was testing, I got the following error:
File "scripts/query_creator.py", line 134, in <module>
"-b", config['bz_api_key'],
KeyError: 'bz_api_key'
README needs to change from 'bugzilla_api_key' to 'bz_api_key'

README change for KeyError: bz_api_key

---

auto_nag/tests/test_phonebook.py

@sylvestre 
The self.demo_dict we treat as a primary Dict, if there is any mess up in the people.json, we could catch it with this. 
by the way phonebook.py is just reading that people.json and processing it. In tests also if we are doing the same, then there is no pint in testing. Isn't it?
We  make sure that people.json processing done by Phonebook is correct by comparing this dict(self.demo_dict) with the desired output; Kind of testing the methods and Testing the people.json also :)

Bztools nosetests phonebook

---

auto_nag/bugzilla/utils.py
auto_nag/scripts/email_nag.py
auto_nag/scripts/query_creator.py
auto_nag/scripts/rm_query_creator.py
auto_nag/tests/test_email_nag.py

Instead of a per-query show_summary boolean, check whether each bug is
restricted to a particular group, and include the title in the nag email
if not.
This also means the summary won't be shown anymore for restricted bugs
in the RelMan "fixed without uplifts" status mail.
Closes mozilla/relman-auto-nag#68

Show summary for non-restricted bugs

---

auto_nag/scripts/email_nag.py

template_params[query]['buglist'] is a list of dicts (one per bug), not
a dict.
This change assumes that if a bug dict has an 'affected' key, all of them do.

Fix sorting by affected versions

---

auto_nag/scripts/query_creator.py

Part of the queries were using
https://wiki.mozilla.org/Template:ESR_VERSION while some others (and the
email text) hardcode 45.  Let's not.
Fixes #78

Stop hardcoding ESR version

---

auto_nag/scripts/email_nag.py
templates/tracked_affected_email

Provides an easy way to get an updated list.
Fixes #87

Include query URL in tracked_affected_email

---

auto_nag/scripts/query_creator.py

Fixes 0db6c130deba68800fad9e6cd9467ff5fb3ee5aa "Use product-details instead of
the wiki"

Fix NameError when we have a "next" ESR

---

auto_nag/scripts/email_nag.py
auto_nag/scripts/phonebook.py

Remove special cases for people who are no longer at Mozilla, and for the
"general@js.bugs" assignee which doesn't look like it's used nowadays.

Remove no-longer-necessary hacks

---

auto_nag/tests/_get_credential.py

Rather than adding the path to the auto_nag/bugzilla package to
sys.path, use the actual project root path, and then import stuff from
auto_nag.bugzilla.

Make sys.path hack in _get_credentials.py script slightly less horrible

---

tox.ini

Allows running e.g. "tox -- --pdb" to get extra args to nosetests.

Pass extra arguments from tox to the test command

---

auto_nag/bugzilla/models.py
auto_nag/scripts/attach.py
auto_nag/scripts/email_nag.py

Like comment authors, flag setter and requestee are now plain strings
instead of User objects.  While I'm there, handle groups properly so we
don't treat all bugs as restricted.

Handle groups and flags properly with bugzilla REST API

---

.gitignore
auto_nag/scripts/configs/tools.json
auto_nag/scripts/leave_open.py
auto_nag/scripts/no_assignee.py
auto_nag/utils.py

Just add a file tools.json in auto_nag/scripts/configs which contains:
{
"no_assignee":
{
"receivers":
[
"calixte@mozilla.com",
"sylvestre@mozilla.com"
],
"days_lookup": 7
},
"leave_open":
{
"receivers":
[
"calixte@mozilla.com",
"sylvestre@mozilla.com"
],
"days_lookup": 7
}
}

Add a config file for tools like no_assignee and leave_open

---

auto_nag/scripts/no_assignee.py
requirements.txt

* the strategy is to get commenters in the bug when we don't have any patch (phab, ...) and try to match commenter and hg patchers.
* when we've several potential assignee then get the one who have the max of comments
* use jaro-winkler similarity to try to find similarity in emails between hg people and bz people

Improve no-assignee tool

---

requirements.txt

Libmozdata 0.1.49 fixed a bug when getting invalid dates for release_owners stuff.

Update requirements for libmozdata (0.1.49)

---

auto_nag/scripts/no_assignee.py

The use case:
https://bugzilla.mozilla.org/show_bug.cgi?id=1526332
the bot changed the assignee to Cosmin but he doesn't want to be the assignee, so don't assign again.

No assignee: don't change assignee again

---

auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json

Example output:
```
The bug: 1530408 will be autofixed with:
{'product': 'WebExtensions', 'cc': {'add': ['sledru@mozilla.com', 'mcastelluccio@mozilla.com', 'cdenizet@mozilla.com']}}
The bug: 1530647 will be autofixed with:
{'product': 'Toolkit', 'component': 'Password Manager', 'cc': {'add': ['sledru@mozilla.com', 'mcastelluccio@mozilla.com', 'cdenizet@mozilla.com']}}
```

Autofix component

---

auto_nag/scripts/component.py

This is a temporary workaround, but I will remove them directly from bugbug targets.

Skip some products when autofixing

---

auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json

And also skip unuseful suggestions in the email report, not only in the autofix.

Send all component suggestions in the email report (only apply confidence threshold for the autofix)

---

auto_nag/scripts/component.py

In order to make a prediction on a bug, bugbug applies the history of the bug backwards. If we don't make a copy, it will keep suggesting a component for some bugs thinking they are still untriaged.

Make copy to avoid bugbug changing properties of the bugs

---

check_bugbug_version.py
requirements.txt

This will avoid the periodic problem we have where you need to uninstall and reinstall bugbug after an update because of pip's poor support for package URLs.

Use bugbug from PyPI

---

auto_nag/scripts/component.py

For ASSIGNED there is less value as a developer has definitely already seen it and so it was likely already triaged.
For REOPENED, it might be more valuable.

Automatically triage ASSIGNED and REOPENED bugs too

---

auto_nag/scripts/regression.py

We download them, but then we definitely won't mark them as regressions, so we might as well just avoid downloading them altogether.

Don't retrieve bugs which are definitely not regressions

---

auto_nag/bzcleaner.py
auto_nag/scripts/not_landed.py
templates/not_landed_comment.txt

When there are r+ patches and no activity in the bug for 2 weeks, we'll needinfo the assignee (if one) or the main patch attacher with a message like this:
```
There's a r+ patch which didn't land and no activity in this bug for 2 weeks.
:foobar, could you have a look please?
```

not_landed: add a needinfo to the assignee or the main attacher

---

runauto_nag_hourly.sh

This tool is probably too stupid.
We should try to improve the detection of a true str to avoid stupid things like this:
STR:
I'm not a STR

Disable has_str_no_hasstr for the moment

---

auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/defectenhancementtask.py
auto_nag/scripts/regression.py

A very small refactoring to avoid duplicating some code.

Call retrieve_model only once in BugbugScript's constructor

---

auto_nag/utils.py

The consequence is to disable some tools (only the merge day):
Unlanded, Tracking, ... (almost all the old ones)

Don't rely on version numbers when we're the merge day

---

auto_nag/scripts/configs/layout_round_robin.json

Adds round robin configuration for the layout team, pulling calendar JSON data from https://gecko.layout.team

Add round robin config for layout team

---

auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/defectenhancementtask.py
auto_nag/scripts/regression.py
auto_nag/utils.py
templates/defectenhancementtask.html

This does a few things:
1) Decrease minimum confidence threshold for the autofixer to 90%;
2) When the script is not sure between task and enhancement, but it is sure it is not a defect, apply the autofix (previously it was only applying when it was sure about task vs enhancement, but even most humans are not sure about those...).
The classifier got better with the additional data we have collected over the past few weeks (since people started to set the bug type).

Make defectenhancementtask script apply autofix more often

---

auto_nag/round_robin.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/to_triage.py
auto_nag/utils.py

We had no way to just send an email to triage_owners who want to receive a reminder for priorities.
So this patch just add the ability for an owner without round robin to be nagged.

to_triage: add jdescottes

---

.isort.cfg
auto_nag/scripts/configs/tools.json
auto_nag/scripts/regressor.py
requirements.txt
runauto_nag_daily.sh
templates/regressor.html

Depends on https://github.com/mozilla/bugbug/pull/546.
Instead of using Phabricator, I'm simply classifying recently landed commits.
In the future, this will be removed from autonag and put on Taskcluster integrating it with eventlistener, where we already have all the infra in place.

Add a regressor.py script that finds risky recently landed patches

---

.pre-commit-config.yaml

See also https://github.com/mozilla/bugbug/pull/584.

Fix default Python version declaration in pre-commit config

---

auto_nag/erroneous_bzmail.py
auto_nag/multinaggers.py
auto_nag/nag_me.py
auto_nag/people.py
auto_nag/round_robin.py
auto_nag/round_robin_calendar.py
auto_nag/round_robin_fallback.py
auto_nag/scripts/assignee_no_login.py
auto_nag/scripts/code_freeze_week.py
auto_nag/scripts/has_str_no_range.py
auto_nag/scripts/leave_open_no_activity.py
auto_nag/scripts/meta_no_deps_no_activity.py
auto_nag/scripts/newbie_with_ni.py
auto_nag/scripts/to_triage.py
auto_nag/scripts/workflow/multi_nag.py
auto_nag/scripts/workflow/no_priority.py
auto_nag/tests/test_round_robin.py
templates/erroneous_bzmail_email.html

There's an issue with the Hiroyuki Ikezoe's bugmail which is incorrect in either phonebook or in calendar.
So the goal of this tool is to send an email to the main triage owner to inform her/him of the issue.
To avoid to send several emails and since the data (people.py or round_robin_calendar.py) are constant across the same run, this patch make them singleton.

Nag main triage owner in case where a bugzilla email on phonebook or in the calendar is invalid

---

auto_nag/scripts/component.py
auto_nag/scripts/defectenhancementtask.py

Following https://github.com/mozilla/bugbug/pull/670, the classification field
was renamed into class, update the needed scripts.
Wait until https://tools.taskcluster.net/groups/RCUA7UVDSVmZVoiQM948QQ/tasks/B6SiGklhSBOR9hbq_7fxQQ/details has finished before merging this PR.

Update scripts to use new bugbug HTTP answer

---

auto_nag/scripts/defectenhancementtask.py

The filtering was moved to the Bugzilla query.

Remove remove_using_history from defectenhancementtask scripts. Fix #775

---

auto_nag/bugbug_utils.py

In the case we have too many bug ids to classify, we might hit a timeout
making a request to the bugbug HTTP service.

Batch call to bugbug http service. Fix #776

---

auto_nag/scripts/defectenhancementtask.py

There are still quite a bit of mistakes, but I think it's better not to override decisions when they are made with cognition.
So, let's disable the autofix (unless we are 100% sure) until https://bugzilla.mozilla.org/show_bug.cgi?id=1565403 is fixed.

Disable defect/enhancement/task autofix until we can detect if users chose the type

---

auto_nag/scripts/not_landed.py
requirements.txt

We got all the attachments in a bug to and filter them according their content-type.
But in some bugs there are several attachments with video, pictures, ...
So the idea is to not retrieve attachment data but just get the ids of the ones with a correct content-type and in a second time just dl the data.
It requires: https://github.com/mozilla/libmozdata/pull/177

Fix not_landed tool: it was broken because we dl too big attachments in bugzilla

---

auto_nag/scripts/uplift_beta.py

Should remove a part of the noise.
If we still have noise, we can go deeper in the attachments to check if the associated Phab requests are published using Phab api.

[uplift_beta] Check for Phabricator's attachment

---

auto_nag/scripts/configs/tools.json

Until I have time to figure out the wrong classifications.

Make regression script only change the regression keyword when it's really sure

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/spambug.py
auto_nag/scripts/stepstoreproduce.py

We can assume bugs filed by people with `editbugs` are good enough, as they are expert enough bug filers.

Search spam bugs and bugs without steps to reproduce only between bugs filed by people without editbugs

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression_set_status_flags.py
auto_nag/tests/test_regression_set_status_flags.py
runauto_nag_daily.sh
templates/regression_set_status_flags.html

Look for recently filed regressions whose regressed_by field is not
empty.  If the regressing bug landed in the current release or later,
set the new bug's status flags for central/beta/release accordingly, if
they were previously unset.
Fixes #882

Add regression_set_status_flags tool

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/spambug.py
templates/spambug.html

So far we were sending an email with *all* results: both bugs classified as spam and bugs not classified as spam.
I've checked the results for a few weeks, and most of the bugs with low confidence are indeed not spam, so I think it's time to only notify of possibly spam bugs.

Only send email with bugs classified as spam

---

auto_nag/scripts/component.py

Bugbug wrongly learned that the bugs mentioning Fluent should go in Core::Internationalization
because over the past few months all bugs mentioning Fluent are in that component (while
Fluent was being built and starting to be used).
Now that Fluent is ready, bugs to track migrations are no longer filed in that component, but are
filed in the component of the migration.
See https://github.com/mozilla/bugbug/issues/1484.

Don't move Firefox::General bugs to Core::Internationalization

---

auto_nag/scripts/code_freeze_week.py

Back in the day the soft freeze lasted a week, but that hasn't been true
for a while now.  Use merge day as the end date instead of hardcoding a
duration.

Stop soft freeze emails going out after the merge

---

auto_nag/scripts/survey_sec_bugs.py

Background: Some mozillians want to to change the whiteboard tag into [sec-survey+] when they have responded to the survey.
To allow for this, we will query for `[sec-survey` instead of `[sec-survey]` (note the missing closing bracket), when looking for bugs in which we need to query

[sec survey] Check for 'open' whiteboard tag only

---

auto_nag/scripts/has_str_no_range.py

The way they're phrased sounds a bit odd, although the intended meaning was clear.

Remove redundant words from a few messages

---

auto_nag/scripts/configs/layout_round_robin.json

We are moving our triage script to the Mozilla GitHub organization, and changing the URL for the JSON files in the process. This PR updates the config for the layout team appropriately.

Update layout team round robin config

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/fuzzing_bisection_without_regressed_by.py
runauto_nag_daily.sh
templates/fuzzing_bisection_without_regressed_by_needinfo.txt

Fixes #1039
Getting blocking bugs recursively appears to be pretty slow.

Needinfo assignees in bugs filed by fuzzing that have a bisection to ask them to set the Regressed By field

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/good_first_bug_unassign_inactive.py
runauto_nag_daily.sh
templates/good_first_bug_unassign_inactive.html

This creates a rule that automatically unassigns good-first-bugs for no activity for a long time (6 months atm), and leaves a comment saying why.

Add good_first_bug_unassign_inactive rule

---

auto_nag/scripts/uplift_beta.py

Just like bugs with pending uplift requests, there's no need to nag in
this case, e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1688924#c6

uplift_beta: skip bugs with checkin-needed-beta in whiteboard

---

auto_nag/scripts/warn_regressed_by.py

This should almost be useless as all regressions should be defects... but you never know.

Don't restrict warn_regressed_by to defect bugs

---

README.rst
auto_nag/iam.py

- add a pointer towards how to request IAM credentials
- add `search:all` to the list of scopes required: while not needed for
the code to operate, if your credentials are missing the `search:all`
scope, our query results in an Internal Server Error

Improve documentation of IAM requirements

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/missed_landing_comment.py
runauto_nag_daily.sh
templates/missed_landing_comment.html

Go through the mozilla-central pushlog, and warn if a (non-backed-out)
changeset is not mentioned in any comment in the corresponding bug.
Fixes #1063

Look for changesets that are missing the corresponding bugherder comment

---

auto_nag/scripts/missed_landing_comment.py

It's used for the email Subject field.

missed_landing_comment: add missing description

---

runauto_nag_hourly.sh

Otherwise we move some spam bugs in a component first and then close as invalid.

Run the spambug script before the component one

---

auto_nag/scripts/spambug.py

The training only happens on specific products, so there is a chance this will not work so well for other products. If it finds too many false positives, then I will extend the training set to contain all products too.

Enable spam bug detection in all products

---

auto_nag/bzcleaner.py
auto_nag/scripts/close_intermittents.py
auto_nag/scripts/closed_dupeme.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/defect_with_please_or_enable.py
auto_nag/scripts/feature_but_type_defect_task.py
auto_nag/scripts/feature_regression.py
auto_nag/scripts/fuzzing_bisection_without_regressed_by.py
auto_nag/scripts/has_str_no_hasstr.py
auto_nag/scripts/leave_open.py
auto_nag/scripts/leave_open_sec.py
auto_nag/scripts/one_two_word_summary.py
auto_nag/scripts/regression_but_type_enhancement_task.py
auto_nag/scripts/regression_without_regressed_by.py
auto_nag/scripts/stalled.py
auto_nag/scripts/stepstoreproduce.py
auto_nag/scripts/summary_meta_missing.py
auto_nag/scripts/topcrash_bad_severity.py
auto_nag/scripts/untriage_important_sev.py
auto_nag/scripts/workflow/p2_merge_day.py
runauto_nag_daily.sh
templates/leave_open_sec.html

Look for commits referencing security bugs with the leave-open keyword, so someone can double check the landed patch is just a diagnostic; this should avoid missing fixes and backports where e.g. the developer is keeping the bug open for purposes of landing a test later.
To cut down on the noise, this only looks at changes in the previous 2 days.  That should still cover weekends, I think, in case the script only runs Monday-Friday.
The PR also includes an unrelated cleanup for something I noticed while writing this: inspecting the stack in `BzCleaner._set_tool_name` meant that a no-op `__init__` method was required for all tools.  So I'm getting rid of that.

Add leave_open_sec nag

---

auto_nag/mail.py

Adds an `X-Mailer` header to all emails.  This simplifies the authoring
email filters that perform actions on all auto-nag generated content
regardless of sender/subject/etc.

Add X-Mailer email header

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/regressed_by_no_has_regression_range.py

Only add "Has Regression Range" to bugs with non-empty "Regressed By" filed since 30 days before the run

---

auto_nag/scripts/component.py

The Foxfooding component's description is "Bugs found through the
foxfooding program will be filed in this component to be later
triaged to the appropriate buckets."

Consider bugs filed in the Firefox::Foxfooding as untriaged bugs

---

auto_nag/scripts/needinfo_regression_author.py
templates/needinfo_regression_author.html
templates/needinfo_regression_author_needinfo.txt

Fixes #1247
Still left to do: don't needinfo if the regressor author already interacted with the bug (by commenting or doing some other action in the bug).

Needinfo regression author when "regressed by" field is set on new bugs

---

auto_nag/scripts/assignee_no_login.py
auto_nag/scripts/configs/tools.json
runauto_nag_daily.sh
templates/assignee_no_login_needinfo.txt
templates/leave_open_no_activity_needinfo.txt

I added a limit on last activity to avoid a large number of needinfos. We can progressively increase the limit after the first batch of bugs have been handled and we can remove the limit once all the backlog has been resolved.
First step of #266

Enable tool to nag about bugs assigned to inactive accounts

---

auto_nag/scripts/severity_inconsistency.py
runauto_nag_daily.sh
templates/severity_inconsistency.html
templates/severity_inconsistency_needinfo.txt

This should resolve #1290.
The new script should be reflected on the [Autonag wiki page](https://wiki.mozilla.org/Release_Management/autonag). The following is the proposed addition to the wiki page:
**Bugs with inconsistent severity flags**
**Purpose**   | Make sure that bugs severity is consistent with the [accessibility severity](https://wiki.mozilla.org/Accessibility/Triage#Triaging_Firefox_and_Gecko_feature_defects) on the Whiteboard 
--- | ---
**Action** 	| Needinfo the assignee or the triage owner if not assigned yet 
**Code** 	| [severity_inconsistency.py](https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/severity_inconsistency.py)
---------
I have the following questions:
- Do we need to limit the bug type to `defect`? Currently is not.
- Do we need to …

Needinfo for bugs with inconsistent severity flags

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/severity_underestimated.py
auto_nag/utils.py
runauto_nag_daily.sh
templates/severity_underestimated.html
templates/severity_underestimated_needinfo.txt

This should resolve #1184.
**Bugs with underestimated severity levels**
| **Purpose** | Identify bugs whose severity could be underestimated. |
| ----------- | ------------------------------------------------------------- |
| **Action**  | Needinfo the assignee or the triage owner if not assigned yet |
| **Code**    | severity_underestimated.py                                    |
----
This script should request needinfo for bugs that have low severity (`S3` and `S4`) if one of the following exceed the configured threshold:
Also, a report with a list of bugs should be sent to configured recipients.
----
The following scripts are producing similar reports (separately):
- [`several_dups.py`](https://github.com/mozilla/relman-auto-nag/blob/4ac56ae2f84b423b04487b5b61af8d435d3fd37d/auto_nag/scr …

Needinfo for bugs with underestimated severity levels

---

auto_nag/scripts/severity_high_security.py
runauto_nag_daily.sh
templates/severity_high_security.html
templates/severity_high_security_needinfo.txt

This should resolve #1336.
I do not have access to security bugs. Thus I was not able to test the results. The following are needed:
---
**Bugs with high security keywords which are set to low severity**
| **Purpose** | Identify bugs whose severity field is set to S3 or S4 and at the same time have sec-high or sec-critical keywords. |
| ----------- | :------------------------------------------------------------------------------------------------------------------ |
| **Action**  | Needinfo to propose increasing the severity.                                                                        |
| **Code**    | severity_high_security.py                                                                                           |

Needinfo for bugs with high security keywords and low severity

---

auto_nag/bzcleaner.py
auto_nag/nag_me.py
auto_nag/utils.py
requirements.txt

This should fix #1324.
In this PR, we generate short URLs for all queries. Alternatively, we could generate the short URLs only when the length exceeds the threshold (i.e., 512).

Generate short Bugzilla URLs

---

auto_nag/nag_me.py
auto_nag/utils.py

The same function is referenced with different names.

Fix inconsistent function name

---

.pre-commit-config.yaml

A new version of `click` (v8.1.0). One of `black`'s dependencies introduced the following error in `pre-commit` (see https://github.com/psf/black/issues/2964):
```
seed isort known_third_party.............................................Passed
isort....................................................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
File "/Users/smujahid/.cache/pre-commit/repopnfkm2uv/py_env-python3/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/Users/smujahid/.cache/pre-commit/repopnfkm2uv/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 1423, in patched_main
patch_click()
File …
```

Fix black by updating to the lates version

---

auto_nag/bzcleaner.py
auto_nag/erroneous_bzmail.py
auto_nag/next_release.py
auto_nag/round_robin_fallback.py
auto_nag/utils.py

With this PR, tools can declare `additional_receivers` in their configurations. The list of receivers in the `additional_receivers` field will be merged with the common receivers. If a tool declares the `receivers` field, it will replace the common receivers.

Merge additional receivers with the common receivers

---

auto_nag/scripts/configs/tools.json

This PR depends on #1359.
I think there is more room for simplifications. I'm not sure if all tools should use `additional_receivers` instead of `receivers`. Examples:
https://github.com/mozilla/relman-auto-nag/blob/6ca57369d7b287286a00aaa97a841bfd43b59c59/auto_nag/scripts/configs/tools.json#L460-L462
https://github.com/mozilla/relman-auto-nag/blob/6ca57369d7b287286a00aaa97a841bfd43b59c59/auto_nag/scripts/configs/tools.json#L464-L465
https://github.com/mozilla/relman-auto-nag/blob/6ca57369d7b287286a00aaa97a841bfd43b59c59/auto_nag/scripts/configs/tools.json#L467-L468

Simplify the receiver lists

---

auto_nag/scripts/assignee_no_login.py
auto_nag/scripts/configs/tools.json

To avoid adding hundreds of needinfos to triage owners, run the script weekly and add a limit on the number of needinfos.
Fixes #266

Remove last activity limitation for unassigning inactive people from bugs

---

auto_nag/scripts/assignee_no_login.py

I'm not sure if we actually want to do this, maybe we can do it in case we get complaints about the tool.

For old bugs with low priority and low severity assigned to inactive people, unassign without needinfoing the triage owner

---

auto_nag/scripts/configs/team_managers.json

I kept the old name for now; we could drop it later. This will catch cases where the old name is still used (if any).

Adapt our new team name

---

auto_nag/scripts/vacant_triage_owner.py

This will only avoid including Release Management in the CC. Managers will stay in the CC.

[vacant_triage_owner] Do not CC Release Management

---

auto_nag/mail.py
auto_nag/scripts/configs/tools.json

This will make it possible to preview the log files in Gmail without downloading them. Also, the content of the file will be searchable.

Use `.txt` extension for attached log files in emails

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/severity_underestimated.py
templates/severity_underestimated.html

Resolves #1322
<body>
<p>Hi there,</p>
<p>The following bugs have potential higher severity:
<thead>
<tr>
<th>Bug</th>
<th>Summary</th>
<th>Creation</th>
<th>Last comment</th>
<th>Severity</th>
<th>Duplicates</th>
<th>Votes</th>
<th>CC</th>
<th>See Also</th>
</tr>
</thead>
<tbody>
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1762224">1762224</a>
</td>
<td>
Background scripts without extension API calls are not correctly detected in ext-backgroundPage.js
</td>
<td>
7 days
</td>
<td>
2 days
</td>
<td>
S3
</td>
<td >
0
</td>
<td >
0
</td>
<td >
3
</td>
<td bgcolor="#FFB8B8">
5
</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1751159">1751159</a>
</td> …

[severity_underestimated] Include `see_also_count`

---

auto_nag/scripts/crash_signature_confirm.py
runauto_nag_daily.sh
templates/crash_signature_confirm.html

Resolves #1238 
**Automatically confirm bugs that have a crash signature**
| **Purpose** | Fix inconsistency in the status of unconfirmed bugs               |
| ----------- | :----------------------------------------------------------------- |
| **Action**  | Confirm bugs with crash signatures by changing the status to "NEW" |
| **Code**    | crash_signature_confirm.py                                         |

Confirm bugs with crash signatures

---

auto_nag/utils.py

Fallback to URL splitting when Bitly fails on extremely long URLs

---

auto_nag/scripts/affected_flag_confirm.py
runauto_nag_daily.sh
templates/affected_flag_confirm.html

Resolves #270 
We consider here the affected Firefox version flags for the **latest 41 versions**.
**Automatically confirm bugs that have an affected Firefox version flag**
| **Purpose** | Fix inconsistency in the status of unconfirmed bugs.                             |
| ----------- | :------------------------------------------------------------------------------- |
| **Action**  | Confirm bugs with affected Firefox version flags by changing the status to "NEW" |
| **Code**    | affected_flag_confirm.py                                                         |
Finished within ~13 seconds. The results include 179 bugs.
```log
2022-04-12 17:04:19,013 - INFO - Run tool affected_flag_confirm.py
2022-04-12 17:04:32,220 - INFO - Tool affected_flag_confirm.py has finished.
```

Automatically confirm bugs that have an affected Firefox version flag

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression_set_status_flags.py

This way we don't risk missing anything during merge periods.

Make regression_set_status_flags look for bugs created in past 21 days instead of just 7 days

---

auto_nag/scripts/needinfo_regression_author.py

Until #1465 is implemented as a generic solution, we should at least avoid needinfoing inactive
regression author (as it can be pretty common).

Don't try to needinfo regression authors, if they are inactive

---

auto_nag/people.py

This should fix the following error:
```
2022-06-07 12:00:13,724 - ERROR - Tool to_triage
Traceback (most recent call last):
File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 745, in run
self.send_email(date=date)
File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 698, in send_email
self.send_mails(title, dryrun=self.dryrun)
File "/home/rm_bot/relman-auto-nag/auto_nag/nag_me.py", line 167, in send_mails
mails = self.prepare_mails()
File "/home/rm_bot/relman-auto-nag/auto_nag/nag_me.py", line 225, in prepare_mails
person, manager
File "/home/rm_bot/relman-auto-nag/auto_nag/people.py", line 319, in get_management_chain_mails
raise Exception(f"Cannot identify {superior} as a superior of {person}")
Exception: Cannot identify xxxx@xxx.com as a superior of …
```

Handle getting the management chain when the superior and the person are the same

---

auto_nag/scripts/fuzzing_bisection_without_regressed_by.py

This should fix the following [error in `mypy`](https://community-tc.services.mozilla.com/tasks/OZhC-o8mT7GPATruFq4BUA/runs/0/logs/public/logs/live.log):
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
auto_nag/scripts/fuzzing_bisection_without_regressed_by.py:51: error:(B Need type annotation for (B"autofix_regressed_by"(B (hint: (B"autofix_regressed_by: Dict[<type>, <type>] = ..."(B)(B
auto_nag/scripts/fuzzing_bisection_without_regressed_by.py:52: error:(B Need type annotation for (B"bzmail_to_nickname"(B (hint: (B"bzmail_to_nickname: Dict[<type>, <type>] = ..."(B)(B
Found 2 errors in 1 file (checked 119 source files)(B
```

Fix `mypy`

---

auto_nag/scripts/vacant_team_manager.py
auto_nag/scripts/vacant_triage_owner.py
auto_nag/team_managers.py
runauto_nag_daily.sh
templates/vacant_team_manager.html

Add a tool to identify teams with no team managers defined in our mapping and team managers that are no longer there

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/vacant_triage_owner.py

<p>The following components are missing an active triage owner:
<thead>
<tr>
<th>Component</th><th>Team</th><th>Team Manager</th><th>Triage Owner</th><th>Triage Owner Status</th>
</tr>
</thead>
<tbody>
<td>
Core::MFBT
</td>
<td>
Low Level
</td>
<td>
Sylvestre Ledru
</td>
<td>
simon.giesecke@xxxx.xxx
</td>
<td>
Not seen on Bugzilla in last 4 weeks
</td>
</tr>
<tr >
<td>
Firefox::Extension Compatibility
</td>
<td>
Web Extensions
</td>
<td>
Thomas Elin
</td>
<td>
jorgev@xxxx.xxx
</td>
<td>
Not seen on Bugzilla in last 4 weeks
</td>
</tr>
<td>
Firefox::Headless
</td>
<td>
CI and Quality Tools
</td>
<td>
Marco Castelluccio
</td>
<td>
bdahl@xxxx.xxx
</td>
<td>
Account …

Change the thresholds for detecting inactive triage owners

---

auto_nag/scripts/vacant_triage_owner.py
templates/vacant_triage_owner.html

Resolves #1489 
<p>The following components are missing an active triage owner:
<thead>
<tr>
<th>Component</th><th>Team</th><th>Team Manager</th><th>Triage Owner</th><th>Triage Owner Status</th><th>Untriaged Bugs</th>
</tr>
</thead>
<tbody>
<td>
Core::MFBT
</td>
<td>
Low Level
</td>
<td>
Sylvestre Ledru
</td>
<td>
simon.giesecke@xxxx.xxx
</td>
<td>
Not seen on Bugzilla in last 4 weeks
</td>
<td>
<a href="https://bugzilla.mozilla.org/buglist.cgi?resolution=---&severity=--&bug_type=defect&product=Core&component=MFBT">13</a>
</td>
</tr>
<tr >
<td>
Firefox::Extension Compatibility
</td>
<td>
Web Extensions
</td>
<td>
Thomas Elin
</td>
<td>
jorgev@xxxx.xxx
</td>
<td>
Not seen on Bugzilla in last …

[vacant_triage_owner] Show the number of untriaged bugs

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/patch_closed_bug.py
runauto_nag_daily.sh

Fixes #1409 
<p>The following bug received a patch after being closed:
<thead>
<tr>
<th>Bug</th><th>Summary</th><th>Resolution</th><th>Last patch</th>
</tr>
</thead>
<tbody>
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1775480">1775480</a>
</td>
<td>
Add more crash annotations for bug 1772839
</td>
<td>
4 days
</td>
<td>
4 days after resolution
</td>
</tr>
</tbody>
</table>
</p>

Avoid warning when backport patches are attached to closed bugs

---

auto_nag/scripts/reminder.py
runauto_nag_daily.sh
templates/reminder.html
templates/reminder_needinfo.txt

For several purposes, it would be good to be able to have a bot come back and place a reminder on a bug.  This can be used for sec-approval to land a test or to come back and remove a preference after letting it ride the trains.

Add reminder functionality to the autonag bot

---

auto_nag/scripts/configs/gfx_round_robin.json

Corrected round-robin config for component renames made by 1774288

---

auto_nag/scripts/configs/tools.json

It was introduced in e795fea301b5922a4d842c7b8d33bcb3261d918f and removed in dfbdff16e5c74bde062c26767404c23c34c33aac, but the configuration was left there.

Remove regressor script configuration as the regressor script doesn't exist anymore

---

.isort.cfg
auto_nag/bzcleaner.py
auto_nag/scripts/inactive_reviewer.py
auto_nag/user_activity.py
requirements.txt
templates/inactive_reviewer.html
templates/inactive_reviewer_needinfo.txt

Resolves #1382
```wiki
{{AutonagRule
| Rule name = Bugs with inactive patch reviewers
| Purpose   = Unblock bugs by identifying patches that are waiting for review from inactive or unavailable reviewers
| Action    = Needinfo patch authors to find active reviewers
| Source    = inactive_reviewer.py 
}}
```
See https://github.com/mozilla/relman-auto-nag/pull/1531#issuecomment-1184712892

Detect review requests on inactive reviewers

---

auto_nag/scripts/configs/tools.json

Add 'Developer Infrastructure' to the list of products considered by autonag

---

auto_nag/scripts/reminder.py

~~This can be used when none of the other categories are really what you're using it for.~~
This can be used when one should look into removing a deprecated API/feature.
I have a use case for a reminder: Remind me to look into a deprecated functionality in ~3 months.
The existing categories don't really match this.

Add an "deprecation" reminder type

---

auto_nag/scripts/inactive_ni_pending.py

Resolves #1523
Clear a needinfo that is pending on an inactive user.
Since inactive users most likely will not respond; if the missed information is essential and cannot be collected another way, the bug maybe should be closed as `INCOMPLETE`.
For more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#inactive_ni_pending.py).

[inactive_ni_pending ] Clarify the comment when clear a needinfo

---

auto_nag/scripts/inactive_reviewer.py
templates/inactive_reviewer_needinfo.txt

Resolves #1553
The following patch is waiting for review from a reviewer who resigned from the review:
| ID  | Title |  Author | Reviewer Status |
| --- | :---- |  ------ | :-------------- |
| [D71652](https://phabricator.services.mozilla.com/D71652) |  Bug 1624907 - Split tree.css into shadow and non-shadow stylesheets. | [ntim](https://bugzilla.mozilla.org/user_profile?user_id=445472)  |[dao](https://phabricator.services.mozilla.com/p/dao/): Resigned |
:ntim, could you please find another reviewer or abandon the patch if it is no longer relevant?
For more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#inactive_reviewer.py).
The following patch is waiting for review from an inactive reviewer:
| ID  | Title |  Author | Reviewer …

[inactive_reviewer] Clarify the needinfo comment

---

auto_nag/bzcleaner.py

Currently, if the `get_mail_to_auto_ni()` method returns `None` and the bug is not filtered out, autonag will try to put empty changes on Bugzilla. Example:
```
2022-07-26 22:01:23,389 - INFO - The bugs: 1127525
will be autofixed with:
{}
```

Allow needinfo bugs selectively when there are no individual auto-fixes

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/fuzz_blockers.py
runauto_nag_daily.sh
templates/fuzz_blockers.html
templates/fuzz_blockers_needinfo.txt

Resolves #1147 
Depends on #1573
```wiki
{{AutonagRule
| Rule name = Fuzz blocker bugs
| Purpose   = Bring attention to bugs that prevent fuzzing from making progress
| Action    = Send weekly reminder emails and suggest increasing the severity when it is low.
| Source    = fuzz_blockers.py 
}}
```
```
2022-07-26 22:17:17,313 - INFO - Run tool fuzz_blockers.py
2022-07-26 22:17:23,470 - INFO - Tool fuzz_blockers.py has finished.
```
<details>
<summary>Click to expand the dry-run output!</summary><br>
<p>The following bugs are preventing fuzzing from making progress:
<thead>
<tr>
<th>Bug</th><th>Summary</th>
</tr>
</thead>
<tbody>
<td>
<a …

Nag on fuzz blocker bugs

---

auto_nag/bzcleaner.py
auto_nag/config.py
auto_nag/scripts/closed_dupeme.py
auto_nag/scripts/leave_open.py
auto_nag/scripts/stalled.py
auto_nag/scripts/summary_meta_missing.py

Resolves #1404 
To put changes without triggering bugmails, the tool should add ` self.no_bugmail = True` in its contractor to overwrite the field from `BzCleaner`.

Support using nomail Bugzilla account

---

auto_nag/scripts/configs/tools.json

This will make it easier to catch bugs that are spam but filed as security bugs and are moved a few days after they are filed out from security.

Bump days lookup for the spambug tool to 7 days

---

auto_nag/scripts/fuzz_blockers.py

Following up on #1564
Temporary exclude old bugs to avoid adding noise if old bugs are no longer relevant. We could remove the date limitation after reviewing old bugs by the fuzzing team.
<p>The following bugs are preventing fuzzing from making progress:
<thead>
<tr>
<th>Bug</th><th>Summary</th>
</tr>
</thead>
<tbody>
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1781961">1781961</a>
</td>
<td>
Large allocation [@ wgpu_core::device::Device$LT$A$GT$::create_bind_group_layout]
</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1778549">1778549</a>
</td>
<td>
Hit MOZ_CRASH(Bad `packing`.) at /dom/canvas/WebGLFormats.cpp:685
</td>
</tr>
<tr …

[fuzz_blockers] Exclude old bugs

---

auto_nag/scripts/fuzz_blockers.py

This reverts commit c5727e01c8a34afab5939e4453178e50599b5484.
Resolves #1586 
From @pyoor in the [fuzzing room on Matrix](https://matrix.to/#/!fKDCypxwedIOzgALgc:mozilla.org/$E7nsJVb7pYY0ymO_DVohOChIDuN_faAU8iwo3dztQlI?via=mozilla.org&via=matrix.org&via=envs.net):
> I went through all of the open fuzzblockers and either closed the bug, removed the fuzzblocker entry, or verified that it is still a fuzzblock
> I have a few that still exist but the testcase no longer reproduces and I'm in the process of getting a new testcase
> but otherwise we should be good with the current list

Revert "[fuzz_blockers] Exclude old bugs (#1584)"

---

auto_nag/scripts/fuzzing_bisection_without_regressed_by.py
templates/fuzzing_bisection_without_regressed_by_needinfo.txt

Resolves #1475 
**Note:** reviewing commit by commit will be clearer
```
2022-08-05 00:00:21,777 - INFO - Run tool fuzzing_bisection_without_regressed_by.py
2022-08-05 00:00:27,234 - WARNING - No bzmail for Bogdan Tara <btara@xxxx.xxx> in bug 1655511
2022-08-05 00:00:28,715 - WARNING - No bzmail for sotaro <sotaro.ikeda.g@xxxx.xxx> in bug 1716829
2022-08-05 00:00:29,101 - WARNING - No bzmail for Coroiu Cristina <ccoroiu@xxxx.xxx> in bug 1673123
2022-08-05 00:00:39,550 - WARNING - No bzmail for Xidorn Quan <me@xxxx.xxx> in bug 1780676
2022-08-05 00:00:39,731 - WARNING - No bzmail for Henrik Skupin <mail@xxxx.xxx> in bug 1729829
2022-08-05 00:00:39,732 - WARNING - No bzmail for Mats Palmgren <mats@xxxx.xxx> in bug 1729829
2022-08-05 00:00:45,957 - WARNING - No bzmail for Henrik Skupin …
```

Needinfo more than one author to fill regressed_by

---

auto_nag/scripts/regression_set_status_flags.py
auto_nag/tests/test_regression_set_status_flags.py

[regression_set_status_flags] Fix setting the `regression` keyword

---

auto_nag/scripts/tracked_attention.py

Similar to #1634
This will fix the broken link to the comment (it is missing the `c` before the comment number).
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1788174#c13

[tracked_attention] Drop unnecessary comment link

---

auto_nag/scripts/severity_migration.py
runauto_nag_weekdays.sh
templates/severity_migration.html

Resolves #1484 
<details>
<summary>Click to expand the dry-run output!</summary><br>
<p>The following bugs were using the old severity system. The severity now is dropped to let teams retriage them:
<thead>
<tr>
<th>Team Name</th><th>Bug</th><th>Summary</th>
</tr>
</thead>
<tbody>
<td>
Accessibility
</td>
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1623221">1623221</a>
</td>
<td>
Large interactive SVG graph completely deadlocks Firefox
</td>
</tr>
<tr >
<td>
Accessibility
</td>
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1579148">1579148</a>
</td>
<td>
Default behavior of new profiles contain migraine triggers
</td>
</tr>
<td> …

Clear the severity for bugs with old-style severity values

---

auto_nag/scripts/severity_migration.py

This reverts commit 10070e0e6595f247f467517fada3307a4a9254c5 (PR #648) based on Wayne's request on [Metrix](https://matrix.to/#/!xFamLORIeLrxDKGhLS:mozilla.org/$Obl4UxbQPOTSBbw00M_X63_DZP6jjLLqUloL0viqUBk?via=mozilla.org&via=matrix.org&via=totally.rip).

Revert "[severity_migration] Include Thunderbird-related products"

---

auto_nag/scripts/multifix_regression.py

This will fix the following error, where the `keywords` key should not be part of the merged value:
```
2022-10-05 20:32:29,065 - ERROR - regression_but_type_enhancement_task, regression_set_status_flags and needinfo_regression_author: Cannot put data for bug 1793513 (change => 
{
"keywords": { "keywords": { "add": ["regression"] } },
"comment": {
"body": "Set release status flags based on info from the regressing bug 1749625\n\n:gw, since you are the author of the regressor, bug 1749625, could you take a look? Also, could you set the severity field?\n\nFor more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#needinfo_regression_author.py).\n"
},
"flags": [
{
"name": "needinfo",
"requestee": "gwatson@mozilla.com",
"status": "?", …
```

[multifix_regression] Return the values only when merge keywords

---

auto_nag/constants.py

The `blocker` severity has never been part of the severity constants, even before #1652.

Add the `blocker` severity to the severity constants

---

auto_nag/iam.py

Fixes #1609, and at the same time unblocks #1529 and #1677 by adding the `found_on_bugzilla` field in the `people.json` file.
This PR will also solve cases where the Bugzilla account was changed or not linked, and the user currently uses their Mozilla email for their Bugzilla account.

[people] Check Bugzilla accounts for employees

---

auto_nag/iam.py

This fixes #1529 and fixes #1677 for autonag. If the unlinked/new Bugzilla account is based on a Mozilla email, it will be automatically detected.

[people] Always search Bugzilla accounts using Mozilla emails

---

auto_nag/scripts/bisection_without_regressed_by.py

Exclude bugs from the Testing::mozregression component in the bisection_without_regressed_by tool

---

auto_nag/scripts/regression_new_set_nightly_affected.py
runauto_nag_weekdays.sh
templates/regression_new_set_nightly_affected.html

Resolves #1506
Dry-run: [Bugzilla query](https://bugzilla.mozilla.org/buglist.cgi?resolution=---&resolution=FIXED&bug_status_type=notequals&bug_status=UNCONFIRMED&keywords=regression&f1=creation_ts&o1=greaterthan&v1=-7d&f2=creation_ts&o2=lessthan&v2=-2d&f3=regressed_by&o3=isempty&f4=cf_status_firefox_nightly&o4=equals&v4=---&f5=cf_status_firefox_beta&o5=equals&v5=---&f6=cf_status_firefox_release&o6=equals&v6=---&include_fields=id&include_fields=summary&include_fields=groups&f7=status_whiteboard&o7=notsubstring&v7=%5Bno-nag%5D&product=Core&product=Developer+Infrastructure&product=DevTools&product=External+Software+Affecting+Firefox&product=Fenix&product=Firefox&product=Firefox+for+iOS&product=Firefox+Build+System&product=GeckoView&product=JSS&product=NSPR&product=NSS&product=Remote+Protocol …

Set nightly status flag to `affected` on newly filed regression bugs

---

auto_nag/scripts/close_intermittents.py

From the last run:
>  The tool close_intermittents has been aborted because it was attempting to apply changes on 214 bugs. The maximum number of changes allowed for this tool is 50.
The typical range for this tool in recent weeks is between 190 and 280. We run this tool once a week (on Tuesdays).

[close_intermittents] Increase the changes limit

---

auto_nag/scripts/regression_set_status_flags.py

Follow up to fix #1535
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1798014#c63

[regression_set_status_flags] Don't consider `---` for latest status

---

auto_nag/scripts/duplicate_copy_metadata.py
auto_nag/utils.py
runauto_nag_hourly.sh
templates/duplicate_copy_metadata.html

Resolves #1706 
The bot will be acting only on recently closed or changed bugs (touched within the previous hour).
```wiki
{{AutonagRule
| Rule name = Copy metadata from duplicates
| Purpose   = Increase the visibility of important information after closing a bug as a duplicate
| Action    = Copy missed metadata from duplicate bugs
| Source    = duplicate_copy_metadata.py 
}}
```

Copy accessibility related metadata from duplicate bugs

---

auto_nag/scripts/assignee_no_login.py

Use HIGH_PRIORITY and HIGH_SEVERITY constants from the constants module instead of redefining them

---

auto_nag/scripts/assignee_no_login.py

When the stalled keyword is present and the assignee is inactive, clear the assignee without needinfoing the triage owner

---

auto_nag/constants.py

Given that priority is used inconsistently across teams, I think the only think we can rely upon is that P1 is high priority. So I propose to remove P2 from the high priority list.

Don't consider P2 as high priority

---

auto_nag/scripts/duplicate_copy_metadata.py

The query is getting bigger and becoming more error-prone. Since we already doing the filtering on the client side and the number of duplicate bugs in a week is limited (i.e., 77 bugs in the last 7 days), it could be better to drop the query filtering.

[duplicate_copy_metadata] Simplify the query

---

.isort.cfg
.pre-commit-config.yaml

Same as https://github.com/mozilla/bugbug/pull/3189

Remove seed-isort-config as it's no longer needed since isort 5

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/variant_expiration.py
auto_nag/utils.py
requirements.txt
runauto_nag_weekdays.sh
templates/variant_expiration.html
templates/variant_expiration_nag.html
templates/variant_expiration_needinfo.txt

Resolves #1623 
Example on Allizom: [bug 1632600](https://bugzilla-dev.allizom.org/show_bug.cgi?id=1632600)
```wiki
{{AutonagRule
| Rule name = Follow up on expiring variants
| Purpose   = Drow the attention to expired variants
| Action    = File a bug before the variant becomes expired and send reminders after the variant expiration date
| Source    = variant_expiration.py 
}}
```

Follow up on expiring variants

---

requirements.txt

Bump python-dateutil from 2.5.2 to 2.8.2

---

auto_nag/constants.py
auto_nag/scripts/topcrash_add_keyword.py
auto_nag/scripts/topcrash_bad_severity.py
auto_nag/utils.py

Resolves #1811
If the `topcrash` keyword was removed earlier by autonag:
- Do not needinfo to increase the severity (suggested by @amccreight).
- Apply more restrictive criteria (e.g., top 10 crashes will be top 5 crashes)
- Adjust the wording

Be more restrictive when re-adding topcrash keywords

---

auto_nag/utils.py
requirements.txt

Generate the release cycle span based on the Firefox Trains API instead of the wiki page

---

auto_nag/scripts/tracked_attention.py

Generate the soft freeze date  based on the Firefox Trains API instead of the wiki page

---

auto_nag/round_robin_calendar.py

Fixes #1922 
With this, we will get the Bugzilla email from the `people.json` file instead of the JSON calendar. As a result, we will have the following benefits:
- We will not have an error if the calendar lists Mozilla email instead of Bugzilla email
- Only employees can be set as triage owners (more secure)
@marco-c are you aware of any case where limiting the triagers to employees could be a problem? We already have this behaviour for ICS calendars.

[round_robin_calendar] Ignore emails from the JSON calendar

---

auto_nag/scripts/moved_to_performance.py
runauto_nag_weekdays.sh
templates/moved_to_performance.html
templates/moved_to_performance_needinfo.txt

Add a tool to request info when a bug is moved to Core::Performance

---

auto_nag/scripts/close_intermittents.py

[close_intermittents] Autoclose intermittents that are P3 too

---

runauto_nag_weekdays.sh

Disabling the `patch_closed_bug` tool temporarily to avoid adding more noize. We should enable the tool back once https://github.com/mozilla/relman-auto-nag/issues/1953 is fixed.

[patch_closed_bug] Disable the tool temporarily

---

bugbot/rules/reminder.py

This was discussed in #developers on matrix.

Send reminders on the day specified instead of the day after

---

bugbot/rules/security_unhide_dups.py
configs/rules.json
scripts/cron_run_weekdays.sh
templates/security_unhide_dups.html

Send weekly list with security bugs that need to be un-hidden

---

bugbot/constants.py
bugbot/rules/inactive_ni_pending.py
bugbot/rules/severity_high_security.py

Don't autoclose security bugs where there is a needinfo on an inactive reporter

---

configs/rules.json

It was already disabled on all existing components. However, we recently added another component called "Knowledge Base", where we also do not want to get nagged, as some flags depend on internal processes.
Instead of adding another Component-exception, let's turn it off for the entire product.

Turn off BugBug for the Web Compatibility product.

---

bugbot/rules/inactive_ni_pending.py

Based on the numbers in https://docs.google.com/spreadsheets/d/1rRU8JAwaKKwgTiYL1NI7cS1XOgB8JF-2KMXZfVpplH8, the number of actions for the next three weeks will be more than 63 (not considering new cases). Increasing the limit will avoid having the rule aborted.

[inactive_ni_pending] Increase the limit from 50 to 100

---

bugbot/rules/uplift_beta.py
scripts/cron_run_weekdays.sh

This PR adds workarounds for #1953 and #2167.

Restore previous workarounds for out-of-sync uplift flags

---

bugbot/mail.py

This patch supplies an ssl context to the `SMTP_SSL` constructor, which enables certificate verification. The default context will use the system's trusted CA certificates. See https://docs.python.org/3/library/ssl.html#ssl-security for more.
Kudos to Martin Schobert and Tobias Ospelt of Pentagrid AG for reporting to Mozilla Security.
It looks none of the item in the checklist are really applicable here.

Ensure SMTP over SSL verifies the server certificate

---

bugbot/rules/variant_expiration.py

Fixes #2206 
When the attachment is a link to Phabricator, the value of `is_patch` will be `0` since the attachment itself is not a patch. Therefore, using `is_patch` to determine if an attachment is a patch will prevent the bot from recognizing that there is a patch attached.

[variant_expiration] Do not rely on `is_patch` to identify patches

---

bugbot/rules/topcrash_highlight.py

This should prevent unnecessary noise until we fix the bug in https://github.com/mozilla/bugbot/issues/2100

[topcrash_highlight] Disable re-adding top crash keywords

---

bugbot/crash/analyzer.py

Fixes #2258 
It's a stupid bug where the constant gets created as a `generator` instead of a `tuple`. As a result, the first time we call the `is_near_allocator_address()` function, we get a correct result, but subsequent calls always return `False`.

[file_crash_bug] Fix detecting addresses with near allocator poison values

---

bugbot/rules/lot_of_comments.py
configs/rules.json
scripts/check_rules_on_wiki.py
scripts/cron_run_weekdays.sh
templates/lot_of_comments.html

Dry run:
```
****************************
* DRYRUN: not sending mail *
****************************
Receivers: ['calixte@mozilla.com', 'sylvestre@mozilla.com', 'mcastelluccio@mozilla.com', 'smujahid@mozilla.com', 'release-mgmt@mozilla.com']
Message:
Content-Type: multipart/mixed; boundary="===============0348191179176360971=="
MIME-Version: 1.0
From: xxx@xxxx.xxx
To: calixte@mozilla.com, sylvestre@mozilla.com, mcastelluccio@mozilla.com, smujahid@mozilla.com, release-mgmt@mozilla.com
Subject: [bugbot] Bugs with several comments for the last 52 weeks for the 2023-11-13
Cc:
Bcc:
X-Mailer: bugbot
--===============0348191179176360971==
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
<!DOCTYPE html>
<html lang="en-us">
<head>
<meta charset="utf-8"> …
```

add a new rule to notify bugs with a lot of comments

---

scripts/cron_run_hourly.sh

Reorder hourly rules to run `file_crash_bug` before `component`

---

bugbot/rules/file_crash_bug.py

[file_crash_bug] Always add the regressor author to CC

---

bugbot/rules/assignee_no_login.py
bugbot/rules/to_triage.py
bugbot/rules/workflow/no_severity.py
bugbot/rules/workflow/p1_no_activity.py
bugbot/rules/workflow/p1_no_assignee.py
bugbot/rules/workflow/p2_merge_day.py
bugbot/rules/workflow/p2_no_activity.py
bugbot/rules/workflow/p3_p4_p5.py
templates/assignee_no_login.html
templates/no_severity.html
templates/p1_no_activity.html
templates/p1_no_assignee.html
templates/p2_merge_day.html
templates/p2_no_activity.html
templates/p3_p4_p5.html
templates/to_triage.html

Use `product::component` to refer to components in all emails

---

bugbot/round_robin.py
bugbot/round_robin_calendar.py

Resolves #2300 
Instead of crashing, with this PR, we will have something like the following:
```
2023-12-14 22:22:49,032 - ERROR - Invalid duty start date for the Performance Engineering team: day is out of range for month: 2023-02-29
```

[round_robin] Do not crash on invalid duty start dates

---

README.rst

Added instructions within the README file for setting up pre-commit, ensuring code formatting consistency before each commit.

Add Pre-Commit Configuration Instructions to README File

---

bugbot/iam.py

Fix #2323 
This will prevent the mismatch when an email address on Bugzilla includes uppercase characters.

[iam] Use lowercase when matching emails

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py
templates/file_crash_bug_description.md.jinja

Resolves #2307 
This PR implements the following:
- Detect PHC crashes
- File them as security bugs
- Since they are security, a bug will be filed even when the crash volume is small
- The bug description will highlight whether the crash is related to PHC
- The filed bugs will block the [PHC meta bug](https://bugzilla.mozilla.org/show_bug.cgi?id=PHC)

[file_crash_bug] Detect and highlight PHC crashes

---

bugbot/rules/uplift_beta.py
scripts/cron_run_weekdays.sh

The workarounds were implemented to mitigate [bug 1825961](https://bugzilla.mozilla.org/show_bug.cgi?id=1825961).
This PR will close #1953. Also, it will mitigate #2275 for the `uplift_beta` rule since we are dropping the impacted code. However, now we are enabling `patch_closed_bug`, it will be impacted by #2275 (the tool could fail).

Drop workaround related to missing uplift approval flags

---

bugbot/crash/analyzer.py

[crash/analyzer] Failback to reports from crash clouseau

---

configs/team_managers.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1889160

Change 'Search and New Tab' name to 'Search Next Generation'

---

bugbot/people.py
bugbot/team_managers.py
tests/test_round_robin.py
tests/test_user_activity.py

This should simplify using the classes outside BugBot.

Support dependency injection on the People and TeamManagers classes

---

bugbot/round_robin.py

Resolves #1982.
Currently an error is logged in `bugbot/round_robin.py` when a product-component pair do not have a triage owner. However, it is expected that `Firefox::Untriaged` has no assigned triage owner. Thus, if the product-component pair is `Firefox::Untriaged`, the error logging is avoided.

Remove logging error for missing triage owner for `Firefox::Untriaged`

---

bugbot/rules/crash_small_volume.py

Resolves #1684.
Autoclears the `needinfo` flag to increase the severity of the bug when the `topcrash` keyword is dropped.

Autoclear needinfo top crash

---

bugbot/rules/not_landed.py

Resolves #1625.
Exclude patches that depend on other patches (in Phabricator) from nagging/setting needinfo when running the `not_landed.py` rule.

Exclude patches that depend on other patches

---

bugbot/rules/component.py
configs/rules.json

Resolves #2398.
Intended to use the Fenix-specific component classifier model from [mozilla/bugbug#4172](https://github.com/mozilla/bugbug/issues/4172) to move bugs that already exist in `Fenix:General` or have been classified in `Fenix:General` by the general `component` model to the other Fenix components.
**NOTE:** Dependent on [mozilla/bugbug#4172](https://github.com/mozilla/bugbug/issues/4172) to be merged first to use the Fenix-specific component classifier model.

Use the new Fenix components model to move bugs out of Fenix:General

---

bugbot/rules/webcompat_platform_without_keyword.py
templates/webcompat_platform_without_keyword.html

Core platform bugs which have known site breakage are those that:
* Have the webcompat:platform-bug keyword set OR
* Block a bug in the Web Compatibility :: Knowledge Base component
Because that's not easy to express as a single bugzilla query, add a rule to ensure that any bug defined by its relationship also has the keyword set, so that other users can simply use a keyword query to find all these bugs.

Add rule to set webcompat:platform-bug keyword on KB entry blockers

---

bugbot/rules/workflow/no_severity.py

Resolves #1596.
The temporary code added to batch triage old bugs with no severity set is no longer needed as we are past the designated removal date. This code was responsible for incrementally including older bugs in triage batches.

Removed code for triaging old bugs with no severity set

---

bugbot/rules/not_landed.py

Resolves https://github.com/mozilla/bugbot/issues/1673.
Prevents BugBot from requesting needinfo when a patch has been backed out.

[not_landed] Prevent requesting needinfo for backed out patches

---

bugbot/bzcleaner.py
bugbot/rules/inactive_ni_pending.py
bugbot/user_activity.py

Resolves #1580.
Currently, the `inactive_ni_pending` rule considers a user to be inactive and/or absent after 26 weeks. This PR intends to consider new Bugzilla users to be inactive/absent after 4 weeks.

[inactive_ni_pending] Consider new Bugzilla users to be inactive/absent in a shorter period of time

---

bugbot/rules/severity_high_security.py

Don't nag about sec-high bugs with lower bug severity if the feature is disabled. 
Resolves #1443

[severity_high_security] Exclude cases where the feature is disabled on release

---

bugbot/rules/close_intermittents.py

Don't close intermittents if they have the 'test-disabled' keyword

---

bugbot/rules/webcompat_platform_without_keyword.py
requirements.txt

This is considered the canonical source for the list of webcompat core bugs, so using it as the backend for the bug-bot rules avoids needing to duplicate the logic across multiple systems.

Make webcompat platform bugs without keyword use BQ data

---

bugbot/rules/inactive_ni_pending.py
bugbot/user_activity.py

Resolves #2515.
Introduces two new statuses `INACTIVE_NEW` and `ABSENT_NEW` to remove the second parameter in `get_string_status()`.

[user_activity] Removed `user_creation_time` parameter in `get_string_status()`

---

bugbot/rules/uplift_beta.py

Resolves #1666.
Removes the initial Bugzilla search parameter to exclude any bug with a needinfo flag and instead introduces a filter to exclude any bug with a needinfo flag requested to the bug assignee, while including the rest.

[uplift_beta] Include bugs with needinfos not requested to the bug assignee

---

configs/rules.json
templates/perfalert_inactive_regression_needinfo.txt

This patch adds additional emails to send to for changes made by the `perfalert_inactive_regression` rule. It also adds an additional blank line to the needinfo comment.

Add additional emails to send to for perfalert_inactive_regression.

---

bugbot/rules/perfalert_resolved_regression.py
configs/rules.json
scripts/cron_run_daily.sh
templates/perfalert_resolved_regression.html
templates/perfalert_resolved_regression_needinfo.txt

This PR adds a new rule to monitor perfalert resolution changes. It will send out an email which provides a summary of all the performance alerts which have had their resolution changed within the last day. It includes the resolution comment, and author in the email as well.

Add new rule for monitoring performance alert resolution changes.

---

bugbot/gcp.py
bugbot/rules/webcompat_platform_without_keyword.py
bugbot/rules/webcompat_sightline.py
scripts/cron_run_hourly.sh
templates/webcompat_sightline.html

Add whiteboard flag to webcompat sightline bugs

---

templates/perfalert_resolved_regression.html

This patch fixes an issue in the resolved performance alerts rule to mention in the previous day instead of in the last week.

Fix wording in the resolved alerts rule email.

---

bugbot/rules/perfalert_inactive_regression.py
templates/perfalert_inactive_regression_needinfo.txt

This patch adds some additional text to the needinfo to ask the developer to close the bug as WONTFIX if it's appropriate, and provides some documentation to help them with this decision.
At the same time, a `backlog-deferred` keyword check is added to prevent bugbot from making needinfo's on bugs who have this set. It signifies that the regression is valid, needs to be fixed or better understood, but won't be immediately fixed. It's not mentioned in the needinfo comment since it should be used sparingly, and in cases where this keyword is set, a follow-up bug can usually be made to look into the issue while resolving the alert as a WONTFIX.
Furthermore, locally, private regressors cause failures so the retrieval of the regressor email is changed to use a get instead.

Mention resolving perfalert as WONTFIX, and don't needinfo on bugs with backlog-deferred keyword.

---

bugbot/rules/assignee_no_login.py

Resolves #1759.
Depends on #2515 to remove the TypeError.

Clear inactive assignee for old high-priority bugs without needinfo

---

bugbot/rules/webcompat_score.py
scripts/cron_run_daily.sh
templates/webcompat_score.html

This sets the cf_webcompat_score field to match a value computed in BigQuery.

Add webcompat_score rule

---

bugbot/round_robin.py
bugbot/rules/no_assignee.py

This PR adds include_fields to only retrieve fields we actually need in the following files :
- bugbot/rules/no_assignee.py
- bugbot/round_robin.py
Fixes #1102

chore: use include_fields in round_robin and no_assignee

---

bugbot/rules/perfalert_resolved_regression.py
templates/perfalert_resolved_regression.html

This patch changes the perfalert resolution rule to check for some additional cases where a comment may have already been provided. Specifically, it now checks for the following:
1. The status author made a comment at the same time as changing the resolution.
2. The status author made a comment just before changing the resolution.
3. Another user provided a resolution comment just before the resolution was made (checked with keywords).
The code was also modified to make it simpler to add more checks in the future.

Add logic to check deeper for perfalert resolution comments.

---

bugbot/rules/component.py

Resolves #2585.
Added explicit `continue` for originally `Fenix::General` bugs not being reclassified to anything else to avoid being "moved" to `Fenix::General` again. (Also applicable to all bugs that are being moved to the same product component pair)

[component] Added explicit skip for Fenix::General bugs not being reclassified

---

configs/rules.json

This adds the `additional_receivers` for the fuzzblockers rule with just one entry (myself)
I would like to do this to get better insights into where our fuzzing is limited by new and existing fuzzblockers.
**I think none of the above applies.** I am not changing behavior, but just adding an email address.

Add fbraun to additional_receivers for fuzzblockers

---

scripts/cron_run_weekdays.sh

Disabled missed_landing_commits rule until metadata used is correct again

---

bugbot/rules/webcompat_platform_without_keyword.py

If an webcompat site report bug is:
* Blocked on an open platform bug
* Not in the needs:diagnosis state
* Does not have the webcompat:platform-bug keyword, and has never had that keyword in the past.
Then it is probably supposed to have the webcompat:platform-bug keyword as it fits the criteria for being considered a webcompat bug likley to be fixed by a platform change.
We don't include bugs where the keyword was previously removed because there are instances where a platform fix would offer a partial solution, but is not on the critical path to a full fix (e.g. if the site is blocking firefox in part due to some feature that's easy to avoid or polyfill).
Also, to avoid a potential race condition, we only update bugs if they haven't themselves been updated since the last import of the …

Set webcompat:platform-bug on site reports likely to be platform bugs

---

bugbot/rules/web_platform_features.py
bugbot/rules/webcompat_score.py
scripts/cron_run_daily.sh
templates/web_platform_features.html

We generally want one platform bug for each web-feature we might implement. Once we know the web-feature associated with the bug, we can automatically ensure that we link to a lot of data about the feature, including the entry in the web-features-explorer and the spec URL. In some cases we also know the standards position, and can also ensure that's linked in the See Also field.
For simplicity the linked data we pull from BigQuery uses full string matches on the URLs, but for actual linking we just compare host and pathnames, so we don't duplicate links with different fragments or similar.

Add a rule to add See Also links to bugs tagged with web-features

---

.github/dependabot.yml

Follow up on https://github.com/mozilla/bugbot/pull/2695
Changed the package-ecosystem from pip to uv in Dependabot configuration to manage Python dependencies. This aligns with the project's current dependency management approach.
Follow on on

Update Dependabot to use uv for Python dependencies

---

bugbot/rules/webcompat_platform_without_keyword.py

Fixes #2701
Replaces `datetime.fromisoformat` with `dateutil.parser.parse` for parsing `bug['last_change_time']`, ensuring UTC handling.

Update bug last change time parsing logic

---

bugbot/rules/web_platform_features.py

Fixes #2715 
Changed the assignment of the 'see_also' field to use a dictionary with an 'add' key instead of concatenating lists. Bugzilla only allows "add" and "remove" operations on list-type fields.

Update see_also field to use dict with 'add' key

---

bugbot/rules/moved_to_performance.py

Don't ask users for perf information when the "Performance Impact" is "none"

---

configs/rules.json

Being in the "common" receivers, it makes it hard for me to see the actual emails I should look at because they impact my team.

Remove mcastelluccio from receivers
