mozilla/bugbot

README.rst

This change only started working, please let me know your thoughts.

Example dictionary structure change in README

---

auto_nag/tests/test_models.py

@sylvestre Please let me know this tests for models.py is enough, it is not yet completed. I thought after getting your feedback, I will write rest of the tests for this module.

Tests for models

---

auto_nag/tests/test_models.py

Tests for models completed and removed unnecessary(repeated) lines of code.

tests for models: completed

---

auto_nag/scripts/automated_release_emails.py

'__name__ == __main__' / deleted unnecessory variable / config parsing
in to local

made automated_release_emails into a stand-alone module by adding

---

auto_nag/scripts/query_creator.py
auto_nag/tests/test_query_creator.py

This will help to write tests for Cleanup method straight forward. Otherwise I have to add Exception decorator in tests.

Exception handling in cleanUp method

---

auto_nag/bugzilla/utils.py
auto_nag/scripts/query_creator.py
auto_nag/scripts/rm_query_creator.py
auto_nag/tests/test_query_creator.py

https://github.com/mozilla/relman-auto-nag/issues/64

Bztools issue 64

---

auto_nag/scripts/email_nag.py
auto_nag/tests/test_query_creator.py

This way bugs affecting only release all come before bugs affecting
release and beta, themselves coming before bugs affecting only beta.

Sort bugs according to the full list of affected versions

---

auto_nag/scripts/query_creator.py

auto nag will still fail if the wiki is down because of 
cycle_span = getTemplateValue("https://wiki.mozilla.org/Template:CURRENT_CYCLE")
but this is the first step

Use product-details instead of the wiki

---

auto_nag/scripts/email_nag.py

I made a guess as to what the "expected" exceptions are.

Get rid of bare "except" to please flake8

---

auto_nag/scripts/email_nag.py

Don't nag for bugs with a "checkin on $future_date" whiteboard entry

---

auto_nag/bugzilla/agents.py

Fixes #82 
I'm not completely sure we want to do this, but just in case...
maybe it should also have a version?  relman-auto-nag isn't currently versioned/released at all so that's icky too.

Set User-Agent to "relman-auto-nag" for bugzilla queries

---

auto_nag/mail.py
auto_nag/scripts/no_assignee.py
auto_nag/tests/test_email_no_assignee.py
requirements.txt
templates/no_assignee_email.html

The goal is to be nagged daily to update bug assignee.

Add a tool to send an email when fixed bugs with patch landed in m-c have no assignees

---

README.rst
auto_nag/scripts/configs/tools.json
auto_nag/scripts/has_regression_range_no_keyword.py
auto_nag/scripts/leave_open.py
auto_nag/scripts/topcrash_bad_severity.py
runauto_nag.sh
templates/topcrash_bad_severity.html

Also create a common config category

Get the top crashes bug without a proper severity

---

auto_nag/scripts/attach.py
auto_nag/scripts/common.py
auto_nag/scripts/email_nag.py
auto_nag/scripts/feature_regression.py
auto_nag/scripts/has_regression_range_no_keyword.py
auto_nag/scripts/leave_open.py
auto_nag/scripts/no_assignee.py
auto_nag/scripts/phonebook.py
auto_nag/scripts/query_creator.py
auto_nag/scripts/regression.py
auto_nag/scripts/rm_query_creator.py
auto_nag/scripts/topcrash_bad_severity.py
auto_nag/scripts/unaffected_affected_no_reg.py
runauto_nag.sh
templates/feature_regression.html
templates/unaffected-affected-no-reg.html

I would appreciate that you check the query :)

Unaff affect no keyword

---

auto_nag/scripts/version_affected.py
runauto_nag.sh
templates/version_affected.html

Bug with Version set but not status_firefox

---

auto_nag/scripts/no_assignee.py

example: https://bugzilla.mozilla.org/show_bug.cgi?id=1112599

Ignore bugs with the meta keyword

---

auto_nag/scripts/configs/tools.json

example: https://bugzilla.mozilla.org/show_bug.cgi?id=1483229

Also ignore bustage

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/no_crashes.py

- filter bugs with testcase keyword
- filter bugs with recent activity

Fix no crash

---

auto_nag/bzcleaner.py
auto_nag/scripts/assignee_but_unconfirmed.py
auto_nag/scripts/tracking.py
auto_nag/scripts/unlanded.py
auto_nag/utils.py

Fix for https://github.com/mozilla/relman-auto-nag/issues/255

Remove bugs with [no-nag] in whiteboard from the query

---

auto_nag/scripts/tracked_bad_priority.py
runauto_nag.sh
templates/tracked-bad-priority.html

Add a tool for tracked bugs in all channels with a weak priority

---

auto_nag/scripts/missing_beta_status.py
runauto_nag.sh
templates/missing-beta-status.html

Add a tool for missing beta status (with an autofix)

---

auto_nag/scripts/missing_beta_status.py

If nightly & release are verified, we cannot say that beta is verified

---

requirements.txt

The new version contains some minor improvements.

Update bugbug version

---

requirements.txt

Update libmozdata to 0.1.47 to fix too big query for reporter_with_ni

---

auto_nag/bzcleaner.py
requirements.txt

Don't forget to pip install -r requirements.txt.

Humanize last comment datetime

---

auto_nag/scripts/regression.py

Ignore bugs filed by the intermittent failure bot

---

runauto_nag.sh

add "reporter has a needinfo and no activity for the last X weeks"

---

.gitignore
auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression.py
templates/component.html

This is working locally, but it can't be merged yet as the trained model is not uploaded yet.

Add a script to automatically assign components to untriaged bugs 

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression.py

Ignore bugs filed by the wpt-sync bot 

---

auto_nag/scripts/component.py

component: sort by confidence

---

auto_nag/scripts/regression.py

Autofix regressions when confidence is > 0.9

---

auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression.py
templates/regression.html

Report all detected regressions, but use a threshold for the autofix

---

.gitignore
auto_nag/bugbug_utils.py

Move models into a 'models' subdirectory

---

auto_nag/scripts/component.py
auto_nag/scripts/regression.py
requirements.txt

Map conflated components to an existing component

---

auto_nag/scripts/configs/tools.json

Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1532253

Also add Create.* in the one_two_summary checker

---

auto_nag/scripts/component.py

Remove date limitation for the product/component suggestor

---

auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/regression.py

Retrieve comments and attachments in parallel

---

auto_nag/__init__.py
auto_nag/bzcleaner.py
auto_nag/log.py
auto_nag/mail.py
auto_nag/next_release.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/no_assignee.py
auto_nag/scripts/no_crashes.py
runauto_nag_daily.sh
runauto_nag_hourly.sh

The goal is to log ERROR & CRITICAL in a file and send it (when non empty) when the runner finished.

Add a logger and remove prints

---

auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json

For now only recent bugs and with a higher confidence threshold

Assign components for bugs in the 'General' component too

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/has_str_no_hasstr.py
auto_nag/utils.py
runauto_nag_hourly.sh
templates/has_str_no_hasstr.html

Add a new tool to add has_str flag to bugs with a STR

---

auto_nag/scripts/configs/tools.json

Only check bugs changed in the past day

---

.travis.yml

Forgot to remove the execution of the script.

Stop executing removed script

---

auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/regression.py

Cache IDs of already analyzed bugs for a week before re-trying

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/defectenhancementtask.py
templates/defectenhancementtask.html

Run bugbug defect/task/enhancement classifier and compare it with human classification

---

auto_nag/scripts/defectenhancementtask.py

In the defect/enhancement/task script, sort results by what we care about more

---

auto_nag/bugbug_utils.py
auto_nag/scripts/has_str_no_range.py
auto_nag/scripts/missing_beta_status.py

Remove useless function (ignore_bug_summary)

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/defectenhancementtask.py
templates/defectenhancementtask.html

Autofix 'defect -> task/enhancement' when bugbug's confidence is high enough

---

auto_nag/bugbug_utils.py
auto_nag/bzcleaner.py

Don't use and don't update the bug cache for bugbug-based scripts when running in dry mode

---

auto_nag/db.py

Fix for https://github.com/mozilla/relman-auto-nag/issues/592

Add an explicit error msg when the db doesn't exist

---

auto_nag/scripts/defectenhancementtask.py

We can re-enable it after the next retrain.

Disable defect->task autofix for now

---

auto_nag/bzcleaner.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/prod_comp_changed_with_priority.py
runauto_nag_hourly_py3.sh
templates/prod_comp_changed_with_priority.html

Add a new tool to find bugs where the priority has been set before the product::component changed

---

auto_nag/scripts/not_landed.py
templates/not_landed_needinfo.txt

not_landed: avoid to nag when there are open dependencies (depends_on)

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/defectenhancementtask.py

With a higher confidence threshold. We can reduce it after the next retraining.

Reenable defectenhancementtask autofix

---

auto_nag/scripts/missed_uplifts.py

The same code is here two times... (bad copy+paste)

Remove dup code

---

auto_nag/nag_me.py

It's a fix for bug: https://github.com/mozilla/relman-auto-nag/issues/695

The same bug can appear several times in the list so remove dups

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/stepstoreproduce.py
runauto_nag_daily.sh
templates/stepstoreproduce.html

Only sending an email for now until we collect enough labels.
Fixes #654.
Part of #222 and #400.

Add an autonagger to automatically set Has STR for defects

---

.isort.cfg
auto_nag/bugbug_utils.py
requirements.txt

In the last version, models are stored in zstandard format rather than xz.

Update to bugbug v0.0.56

---

.isort.cfg
auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/defectenhancementtask.py
auto_nag/scripts/regression.py
auto_nag/scripts/regressor.py
auto_nag/scripts/stepstoreproduce.py

It's still a work in progress but I get the same output running `python3 -m auto_nag.scripts.component -d` on master and on this branch

Start using the bugbug HTTP service

---

auto_nag/bugbug_utils.py
auto_nag/bzcleaner.py
auto_nag/scripts/component.py
auto_nag/scripts/configs/tools.json

Follow-up on https://github.com/mozilla/relman-auto-nag/pull/733

Cleanup bugbug component script

---

auto_nag/bugbug_utils.py

It was changed by https://github.com/mozilla/bugbug/commit/d00c175d66f38affa1e92276747a3fe5d9fa4435#diff-3264a81024838e86d703b73bc23b2c67R353.

Reply from the bugbug batch API now is under 'bugs'

---

auto_nag/bugbug_utils.py
auto_nag/scripts/component.py
auto_nag/scripts/defectenhancementtask.py
auto_nag/scripts/regression.py
auto_nag/scripts/regressor.py
auto_nag/scripts/stepstoreproduce.py

The remaining use is covered by the regression model directly
https://github.com/mozilla/bugbug/blob/master/bugbug/models/regression.py#L16
I'm gonna tackle https://github.com/mozilla/relman-auto-nag/issues/774 also in this PR

Remove the last bits of `remove_using_history`. Fix 775

---

auto_nag/scripts/configs/dom_workers_storage_round_robin.json

Add Core::DOM: File component into the triage list.

Update DOM:Workers&Storage team triage list

---

auto_nag/scripts/configs/dom_workers_storage_round_robin.json

According to https://bugzilla.mozilla.org/show_bug.cgi?id=1594717.

Updated components names.

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/spambug.py
runauto_nag_daily.sh
templates/spambug.html

This PR still needs revisions.

Add spambug model

---

runauto_nag_common.sh
runauto_nag_daily.sh
runauto_nag_hourly.sh

Keep running scripts when one fails

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/spambug.py

@emceeaich instead of sending an email with the few bugs which are detected as spam with a high confidence, we're going to send an email with all the analyzed bugs and the respective confidence so we can see if there are bugs which are missed by the model (and then investigate why they are missed).

Some improvements to see what the spam bug model is doing

---

auto_nag/scripts/configs/tools.json

would be great to get this in before the survey runs this Wednesday.

Add more volunteers to survey_sec_bugs

---

auto_nag/scripts/leave_open_no_activity.py

For reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1003801#c17
We've a tool for meta with no deps.

[leave-open] Don't nag on meta bug

---

auto_nag/scripts/to_triage.py
auto_nag/scripts/workflow/no_severity.py

This fixes issues #964 and #965

Leave bugs with normal severity out of query

---

auto_nag/scripts/regression_set_status_flags.py
auto_nag/tests/test_regression_set_status_flags.py
templates/regression_set_status_flags.html

Set status flags for regressions in ESR

---

auto_nag/bugbug_utils.py

It is no longer needed since mozilla/bugbug@6815875

Stop chunking requests to bugbug

---

auto_nag/iam.py

I ran the script locally without any errors.

Fix invalid keys with IAM data

---

.isort.cfg
auto_nag/bzcleaner.py
auto_nag/scripts/not_landed.py
requirements.txt

- get a reviewer randomly in the list of patch reviewers
- just add a needinfo

not_landed: Ni reviewer

---

auto_nag/scripts/component.py

So we don't skip bugs that somebody else put in Untriaged

Skip bugs where we already changed the component in the component assignment script

---

auto_nag/scripts/configs/tools.json

Add mhoye as a recipient for spambug notifications

---

auto_nag/scripts/configs/tools.json

Run auto nag script for Remote Protocol product

---

auto_nag/scripts/component.py

Don't move bugs into components they were ever moved out of

---

auto_nag/scripts/no_crashes.py

Skip too long signatures and remove empty chunks

---

auto_nag/scripts/configs/dom_lws_round_robin.json
auto_nag/scripts/configs/tools.json

Changes requested by @jensstutte

Rename DOM:Workers&Storage to DOM:LWS and add more components to its round robin config

---

auto_nag/scripts/spambug.py

Improve the comment when closing a bus as spam

---

auto_nag/scripts/configs/dom_core_round_robin.json
auto_nag/scripts/configs/dom_lws_round_robin.json

Move 'Core::DOM: Window and Location' from DOM LWS to DOM Core

---

auto_nag/scripts/pdfjs_update.py
runauto_nag_daily.sh
templates/pdfjs_update.html

Add a script to automatically link bugs to PDF.js updates

---

auto_nag/scripts/configs/desktop_installer_round_robin.json

Amir is the right fallback here as he's currently managing this team. Figured I'd update the script in case we need it again.

Update triage owner fallback for Desktop Integrations

---

auto_nag/scripts/configs/tools.json

Update list of products to consider

---

auto_nag/scripts/regressed_by_no_has_regression_range.py
runauto_nag_daily.sh

Set "Has Regression Range" to "yes" on bugs where "Regressed By" is set

---

auto_nag/scripts/configs/tools.json

Disable workflow scripts for Fenix

---

auto_nag/scripts/spambug.py

Soften spambug closing message

---

auto_nag/scripts/configs/tools.json

Extend script to unassign inactive people to bugs with last activity within the previous 6 months

---

runauto_nag_hourly.sh

I forgot to actually add it to the run* script in #1284.

Run the needinfo_regression_author script hourly

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/regression_set_status_flags.py

[regression_set_status_flags] Add a list of exceptions for product::component

---

auto_nag/scripts/component.py

Reword text of the comment added when the bot changes a component for a bug

---

auto_nag/db.py
auto_nag/history.py
auto_nag/mail.py
auto_nag/nag_me.py
auto_nag/scripts/leave_open_no_activity.py
auto_nag/scripts/meta_no_deps_no_activity.py

This applies the same feedback from Marco's review in #1313 on the rest of the scripts.

Replace some short variables with full names

---

auto_nag/history.py
auto_nag/scripts/close_intermittents.py
auto_nag/scripts/topcrash_bad_severity.py
auto_nag/scripts/tracked_bad_severity.py

Support enumerated severities in old scripts

---

auto_nag/bzcleaner.py
auto_nag/multinaggers.py
auto_nag/next_release.py
auto_nag/round_robin_fallback.py
run_close_intermittents.sh
run_code_freeze_week.sh
run_survey_sec_bugs.sh
runauto_nag_daily.sh
runauto_nag_hourly.sh

And add a "--no-dryrun" option to actually make changes
Fixes #1333

Make dryrun the default

---

auto_nag/scripts/mismatch_priority_tracking_beta.py
auto_nag/scripts/mismatch_priority_tracking_esr.py
auto_nag/scripts/mismatch_priority_tracking_nightly.py
auto_nag/scripts/mismatch_priority_tracking_release.py

By pointing to the right docs, and by mentioning a possible action to avoid the bot's action.
Fixes #1331

Improve comment for mismatch_priority_tracking_* tools

---

auto_nag/scripts/configs/tools.json

Extend script to unassign inactive people to bugs with last activity within the previous 24 months

---

auto_nag/scripts/needinfo_regression_author.py

Avoid trying to needinfo nobody in the needinfo_regression_author script

---

auto_nag/scripts/assignee_no_login.py
auto_nag/scripts/configs/tools.json

This should mitigate cases like in [bug 1575465](https://bugzilla.mozilla.org/show_bug.cgi?id=1575465).
This PR is based on a discussion with @calixteman.

Avoid frequent changes of a bug assignee

---

templates/regressed_by_no_has_regression_range.html

[regressed_by_no_has_regression_range] Add the missed template

---

auto_nag/scripts/configs/tools.json

Following up on https://github.com/mozilla/relman-auto-nag/pull/1361#issuecomment-1082788066

Use `additional_receivers` instead of `receivers` for all tools

---

auto_nag/bzcleaner.py
auto_nag/scripts/assignee_no_login.py
templates/assignee_no_login_needinfo.txt

This PR is doing a few things to make the tool less noisy. I suggest reviewing each commit in isolation.

Tweak assignee no login filters

---

runauto_nag_daily.sh

Temporarily disabling the tool until we fix  #1409.

[patch_closed_bug] Disable the tool

---

auto_nag/scripts/tracked_needinfo.py

[tracked_needinfo] Exclude bugs with no old needinfos from the email report

---

auto_nag/scripts/feature_but_type_defect.py
runauto_nag_daily.sh
templates/feature_but_type_defect.html

It's common and acceptable for meta bugs to be "task" and have a "feature" keyword

Don't list bugs with "task" type and "feature" keyword

---

auto_nag/scripts/copy_duplicate_info.py

Add a comment when copying signatures from duplicates

---

auto_nag/scripts/configs/tools.json
auto_nag/scripts/uplift_beta.py

Request Beta uplift right away instead of waiting for a few days after Nightly landing

---

auto_nag/multinaggers.py
auto_nag/nag_me.py
auto_nag/people.py
auto_nag/tests/test_escalation.py

CC people in the management chain when escalating nag emails

---

auto_nag/scripts/inactive_ni_pending.py

Resolves #1448 
The following are bugs that will be affected by the comment customization in the next run:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1715753
- https://bugzilla.mozilla.org/show_bug.cgi?id=1538435

[inactive_ni_pending] Customize the comment when the setter is the triage owner

---

auto_nag/scripts/configs/core_general_round_robin.json

Set Thomas as fallback for Core::General

---

auto_nag/scripts/ni_from_manager.py
auto_nag/scripts/regression_set_status_flags.py
auto_nag/tests/test_bzcleaner.py

Avoid crashing when no consistent versions

---

auto_nag/scripts/inactive_ni_pending.py

Cancel needinfo on an inactive user when close a bug

---

auto_nag/scripts/missing_beta_status.py

Set the missing beta status only when nightly and release are affected

---

auto_nag/scripts/uplift_beta.py
templates/uplift_beta_needinfo.txt

Clarifying the comments based on @rvandermeulen's suggestion on Slack.

[uplift_beta] Clarify the comments

---

auto_nag/bzcleaner.py
auto_nag/scripts/assignee_no_login.py
auto_nag/scripts/configs/tools.json
auto_nag/utils.py
templates/assignee_no_login.html

Resolves #1379 
```diff
{{AutonagRule
| Rule name = Assignee is inactive
| Purpose   = Help identify bugs that are assigned to inactive accounts
- | Action    = Needinfo the triage owner
+ | Action    = Reset the assignee, and if the bug has high priority or high severity, needinfo the triage owner
| Source    = assignee_no_login.py
}}
```
```
2022-06-09 18:13:18,677 - INFO - Run tool assignee_no_login.py
2022-06-09 18:14:06,704 - INFO - Tool assignee_no_login.py has finished.
```
[dryrun.html.txt](https://github.com/mozilla/relman-auto-nag/files/8874424/dryrun.html.txt)

[assignee_no_login] Consider all types of inactivity

---

auto_nag/scripts/fuzzing_bisection_without_regressed_by.py

Correct indentation for checking if a range was found

---

auto_nag/scripts/fuzzing_bisection_without_regressed_by.py

Use 'add' to add regressed_by IDs

---

.isort.cfg
.pre-commit-config.yaml
auto_nag/bzcleaner.py
auto_nag/db.py
auto_nag/mail.py
auto_nag/people.py
auto_nag/round_robin.py
auto_nag/utils.py

Resolves #1472 and resolves #1364

Add `mypy` to `pre-commit`

---

auto_nag/scripts/inactive_ni_pending.py

Not: ignoring whitespace changes will show a clearer diff.

[inactive_ni_pending] Consider normal, minor, and trivial severities when closing bugs

---

auto_nag/scripts/missing_beta_status.py

Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1731965#c15.

Remove extraneous dollar signs

---

auto_nag/people.py

[people] Fix duplicate comments

---

auto_nag/scripts/mismatch_priority_tracking.py

Soon this tool will be dropped. Fixing the query in the meantime to maintain a healthy history.

[mismatch_priority_tracking] Fix the query

---

auto_nag/scripts/inactive_ni_pending.py

I think it is better to not land/deploy this until resolving #1483

Add reasoning in the comment when forward inactive needinfos

---

auto_nag/scripts/tracked_attention.py
auto_nag/team_managers.py

[team_managers] Handle components that have same names

---

auto_nag/scripts/inactive_ni_pending.py
auto_nag/utils.py

Ignore bot comments when considering recent activities

---

auto_nag/scripts/pdfjs_update.py

Don't set blocked bugs again after having done it once

---

.isort.cfg
auto_nag/component_triagers.py
auto_nag/round_robin.py
auto_nag/scripts/triage_owner_rotations.py
requirements.txt
templates/triage_owner_rotations.html

Resolves #1491 
Blocked by:
- https://github.com/mozilla/libmozdata/pull/201
```
2022-07-01 00:21:44,468 - INFO - Run tool triage_owner_rotations.py
2022-07-01 00:22:00,730 - INFO - Tool triage_owner_rotations.py has finished.
```
<p>The following triage owners will be automatically assigned:
<thead>
<tr>
<th>Component</th><th>Old Triage Owner</th><th>New Triage Owner</th>
</tr>
</thead>
<tbody>
<td>
Core::CSS Parsing and Computation
</td>
<td>
emilio@xxxx.xxx
</td>
<td>
jwatt@xxxx.xxx
</td>
</tr>
<tr >
<td>
Core::CSS Transitions and Animations
</td>
<td>
boris.chiou@xxxx.xxx
</td>
<td>
jwatt@xxxx.xxx
</td>
</tr>
<td>
Core::DMD
</td>
<td>
continuation@xxxx.xxx
</td> …

Automatically update the triage owner on Bugzilla

---

auto_nag/scripts/tracked_attention.py

[tracked_attention] Fix the email title

---

auto_nag/scripts/configs/team_managers.json

Change the Telemetry team manager

---

auto_nag/scripts/patch_closed_bug.py

Fixes #1538
@dholbert does the new message look good to you?

Soften language for the patch on closed bug tool

---

auto_nag/topcrash.py

[topcrash] Fix a typo in a function name

---

auto_nag/scripts/patch_closed_bug.py

Follow up on https://github.com/mozilla/relman-auto-nag/pull/1542#discussion_r923604791 to fix #1538

[patch_closed_bug] Improve the comment

---

auto_nag/scripts/workflow/no_severity.py

Avoid nagging about the severity on active bugs

---

auto_nag/scripts/inactive_reviewer.py

[inactive_reviewer] Fix parsing previous comments

---

auto_nag/round_robin.py

[round_robin] Fix fetching the CSV file

---

auto_nag/component_triagers.py
auto_nag/round_robin.py

Resolves #1562
<p>The following triage owners will be automatically assigned:
<thead>
<tr>
<th>Component</th><th>Old Triage Owner</th><th>New Triage Owner</th>
</tr>
</thead>
<tbody>
<td>
Core::DOM: Bindings (WebIDL)
</td>
<td>
echen@xxxx.xxx
</td>
<td>
mbrodesser@xxxx.xxx
</td>
</tr>
<tr>
<td>
Core::DOM: Copy & Paste and Drag & Drop
</td>
<td>
htsai@xxxx.xxx
</td>
<td>
mbrodesser@xxxx.xxx
</td>
</tr>
<td>
Core::DOM: Core & HTML
</td>
<td>
htsai@xxxx.xxx
</td>
<td>
mbrodesser@xxxx.xxx
</td>
</tr>
<tr>
<td>
Core::DOM: Editor
</td>
<td>
htsai@xxxx.xxx
</td>
<td>
mbrodesser@xxxx.xxx
</td>
</tr>
<td>
Core::DOM: Events
</td>
<td>
htsai@xxxx.xxx
</td> …

[triage_owner_rotations] Round-robin consistency

---

runauto_nag_daily.sh

Enable the triage owner rotations tool

---

auto_nag/user_activity.py

Fix the inactive users issue

---

templates/assignee_no_login_needinfo.txt

Resolves #1567 
The inactivity includes disabled accounts, no activity on Bugzilla, and no login. So the current wording (even with the number of months) is inaccurate.

[assignee_no_login] Improve the wording for the needinfo comment

---

README.rst

Since the scripts internally use relative paths, the cron jobs need to change the working directory before running the scripts.
```
cat /tmp/autonag-people.log
/home/rm_bot/relman-auto-nag/update_people.sh: line 6: ./runauto_nag_common.sh: No such file or directory
```
```
cat /tmp/autonag-hour.log
/home/rm_bot/relman-auto-nag/runauto_nag_hourly.sh: line 5: ./runauto_nag_common.sh: No such file or directory
/home/rm_bot/relman-auto-nag/runauto_nag_hourly.sh: line 7: venv/bin/activate: No such file or directory
/usr/bin/python: No module named auto_nag
/usr/bin/python: No module named auto_nag.scripts
/usr/bin/python: No module named auto_nag.scripts
/usr/bin/python: No module named auto_nag.scripts
/usr/bin/python: No module named auto_nag.scripts
/usr/bin/python: No module named …
```

[README] Fix paths for cron jobs

---

auto_nag/scripts/configs/tools.json

Remove creation date limitation from the to_triage tool

---

auto_nag/bzcleaner.py
auto_nag/scripts/configs/tools.json
auto_nag/scripts/workflow/no_severity.py

Resolves #1592
We expand the time limitation for the oldest bug  ~3 weeks each month.

[no_severity] Replace the fixed time limitation with an expanding one

---

requirements.txt

Update `libmozdata` to fix the component update request

---

auto_nag/scripts/triage_owner_rotations.py

We want to deploy today, so we are excluding the GFX until confirming with @b0bh00d.

[triage_owner_rotations] Exclude the GFX team until confirming opt-in

---

requirements.txt

Update `libmozdata` to support components that have `/` in their names

---

auto_nag/scripts/fuzz_blockers.py

This should fix cases like https://bugzilla.mozilla.org/show_bug.cgi?id=1735444#c13

[fuzz_blockers] Avoid suggesting increasing the severity more than once

---

auto_nag/bzcleaner.py
auto_nag/multi_autofixers.py
auto_nag/multinaggers.py
auto_nag/scripts/multifix_regression.py
auto_nag/scripts/needinfo_regression_author.py
auto_nag/tests/test_multi_autofixers.py
runauto_nag_hourly.sh

Resolves #1415
**Note:** reviewing commit by commit will be clearer

Merge changes from regression related tools

---

auto_nag/scripts/fuzzing_bisection_without_regressed_by.py

In #1610, we modified the needinfo comment. As a result, the query does not exclude bugs with the new needinfo comment. Shortening the filtering sentence will match the old and new comments.

[bisection_without_regressed_by] Modify the comment filter

---

auto_nag/scripts/component.py

Temporarily disable component assignment for Foxfooding bugs

---

auto_nag/scripts/regression_set_status_flags.py

[regression_set_status_flags] Filter out `UNCONFIRMED` bugs

---

auto_nag/scripts/bisection_without_regressed_by.py
templates/bisection_without_regressed_by_needinfo.txt

Doing @marco-c's suggestion in https://github.com/mozilla/relman-auto-nag/issues/1626#issuecomment-1233467225

[bisection_without_regressed_by_needinfo ] Drop unnecessary comment links

---

auto_nag/scripts/regression_set_status_flags.py

Similar to #1632, resolves #1628

[regression_set_status_flags] Always set the `regression` keyword

---

runauto_nag_weekdays.sh

The tool was introduced in #1451, but it was never enabled.

[topcrash_add_keyword] Enable the tool

---

auto_nag/scripts/severity_migration.py

Following up on #1639
| Team Name               | Number of bugs |
| ----------------------- | :------------: |
| Frontend                |      243       |
| DOM Core                |      108       |
| GFX                     |       83       |
| Layout                  |       68       |
| Search and New Tab      |       58       |
| Crypto                  |       56       |
| OS Integration          |       41       |
| Networking              |       33       |
| Javascript              |       26       |
| Media                   |       20       |
| Other                   |       18       |
| Accessibility           |       14       |
| CI and Quality Tools    |       14       |
| Security Engineering    |       12       |
| Desktop Integrations    |       10       |
| DOM LWS …

[severity_migration] Excluding bugs that have the `crash` keyword

---

auto_nag/scripts/severity_migration.py

Following up on #1639 as suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1789259#c7
| Team Name               | Number of bugs |
| ----------------------- | :------------: |
| Mozilla                 |      473       |
| Frontend                |      243       |
| DOM Core                |      108       |
| GFX                     |       83       |
| Layout                  |       68       |
| Search and New Tab      |       58       |
| Crypto                  |       56       |
| OS Integration          |       41       |
| Networking              |       33       |
| Javascript              |       26       |
| Media                   |       20       |
| Other                   |       18       |
| Accessibility           |       14       |
| CI and Quality Tools    | …

[severity_migration] Include Thunderbird-related products

---

auto_nag/constants.py
auto_nag/scripts/crash_small_volume.py
auto_nag/scripts/fuzz_blockers.py
auto_nag/scripts/inactive_ni_pending.py
auto_nag/scripts/severity_high_compat_priority.py
auto_nag/scripts/topcrash_add_keyword.py
auto_nag/scripts/tracked_attention.py
auto_nag/utils.py

Move priority and severity constants in a separate module

---

auto_nag/topcrash.py

[topcrash] Fix a typo in a method name

---

auto_nag/scripts/topcrash_bad_severity.py

[topcrash_bad_severity] Exclude thunderbird's topcrash

---

auto_nag/scripts/needinfo_regression_author.py

Similar to #1632 and #1635. Resolves #1628.

[needinfo_regression_author] Always set the regression keyword

---

.pre-commit-config.yaml

This should fix te following error:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
File "/root/.cache/pre-commit/repo82d5_7gu/py_env-python3/bin/flake8", line 8, in <module>
sys.exit(main())
File "/root/.cache/pre-commit/repo82d5_7gu/py_env-python3/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/root/.cache/pre-commit/repo82d5_7gu/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
self._run(argv)
File "/root/.cache/pre-commit/repo82d5_7gu/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
self.initialize(argv)
File …
```

Update `flake8` to fix the CI

---

auto_nag/scripts/component.py

Re-enable component assignment for Foxfooding bugs

---

auto_nag/topcrash.py

This mainly affects signatures with zero crashes.

Fix the keys when returning crash signature volumes

---

runauto_nag_weekdays.sh

We should enable the tool back after considering the following:
- Factoring in the age of the bug in the used thresholds 
- #1685 
-  #1688

[severity_underestimated] Disable the tool temporary

---

auto_nag/scripts/meta_summary_missing.py

Don't send bugmail when adding '[meta]' in bug summary

---

auto_nag/scripts/bisection_without_regressed_by.py

[bisection_without_regressed_by] Ignore bugs with the`regressionwindow-wanted` keyword

---

auto_nag/scripts/crash_small_volume.py

[crash_small_volume] Ignore severity changes done by bots

---

auto_nag/scripts/workflow/no_severity.py

Relax time to nag about missing severity

---

auto_nag/scripts/regression_set_status_flags.py

Don't set `affected` flags if the latest version flag is `wontfix` or `fix-optional`

---

auto_nag/scripts/regression_but_type_enhancement_task.py

[regression_but_type_enhancement_task] Justify changing the bug type

---

auto_nag/scripts/close_intermittents.py

[close_intermittents ] Set open status flags to `wontfix`

---

auto_nag/bzcleaner.py
auto_nag/scripts/triage_owner_rotations.py
auto_nag/scripts/triage_rotations_outdated.py
auto_nag/scripts/vacant_team_manager.py
auto_nag/scripts/vacant_triage_owner.py
templates/aborted_preamble.html

Resolves #1570
It will be clearer to review the commits individually and ignore the whitespace changes.
We could increase the limits for tools that may require that before landing this PR.

Limit touched bugs

---

auto_nag/scripts/crash_small_volume.py
auto_nag/topcrash.py

[crash_small_volume] Handle cases where there are no signatures to check

---

auto_nag/scripts/configs/tools.json

Add `Focus` to the list of default products

---

auto_nag/scripts/bisection_without_regressed_by.py
templates/bisection_without_regressed_by_needinfo.txt

[bisection_without_regressed_by] Only suggest investigating the regression for open bugs

---

auto_nag/iam.py

[people] Fix the `found_on_bugzilla` field

---

auto_nag/scripts/fuzz_blockers.py

[fuzz_blockers] Ignore bugs that have the `stalled` keyword

---

auto_nag/scripts/crash_small_volume.py

[crash_small_volume] Do not decrease the severity of `fuzzblocker` bugs

---

auto_nag/scripts/duplicate_copy_metadata.py

This will avoid silently failing when the query has too many bug ids.

[duplicate_copy_metadata] Filter out closed bugs locally

---

auto_nag/scripts/spambug.py

[spambug] Consider only `UNCONFIRMED` bugs

---

auto_nag/scripts/duplicate_copy_metadata.py

This will fix the table rendering, e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1753565#c4

[duplicate_copy_metadata] Fix the table in the comment

---

auto_nag/scripts/inactive_ni_pending.py

[inactive_ni_pending] Reduce the threshold for recent activity to be 5 weeks

---

auto_nag/scripts/inactive_ni_pending.py

[inactive_ni_pending] Relax the conditions to close bugs

---

auto_nag/topcrash.py

Resolve #1780
The wiki diff: https://wiki.mozilla.org/index.php?title=CrashKill/Topcrash&diff=next&oldid=1243880

Update the topcrash criteria for Fenix to reflect the latest update on the wiki

---

templates/duplicate_copy_metadata.html
templates/inactive_reviewer.html
templates/ni_from_manager.html
templates/tracked_attention.html
templates/tracked_needinfo.html
templates/tracked_needinfo_nag.html
templates/tracking.html
templates/tracking_nag.html
templates/triage_rotations_outdated.html

Remove unnecessary margins for lists in email tables

---

auto_nag/scripts/severity_high_performance_impact.py
templates/severity_high_performance_impact.html
templates/severity_high_performance_impact_needinfo.txt

Resolves #1709
```wiki
{{AutonagRule
| Rule name = Severity of performance impacting bugs
| Purpose   = Consistency and help getting traction on bugs with a high impact on performance
| Action    = Needinfo the assignee or the triage owner (if not assigned) to increase the severity
| Source    = severity_high_performance_impact.py 
}}
```

Add a tool to suggest increasing the severity of performance-impacting bugs

---

auto_nag/scripts/spambug.py

Ignore bugs that were moved out of the `Invalid Bugs` product

---

auto_nag/scripts/crash_small_volume.py
auto_nag/topcrash.py

Increase the minimum crashes threshold

---

auto_nag/topcrash.py

[topcrash] Specify the major version to avoid old builds

---

auto_nag/scripts/crash_small_volume.py
auto_nag/topcrash.py

It will be clearer to review commit by commit.

Some refactoring to improve the consistency in the `Topcrash` class

---

auto_nag/scripts/regression_set_status_flags.py

Don't fail when an ESR flag does not exist

---

runauto_nag_weekdays.sh

The tool was introduced in #1786

[severity_high_performance_impact] Enable the tool

---

auto_nag/bzcleaner.py
templates/aborted_preamble.html

This will reduce the possibility of running the tool without using the proxy.

Show the complete command to manually run the tool without a limit

---

auto_nag/scripts/missed_uplifts.py

[missed_uplifts] Tolerate missing ESR status field

---

auto_nag/scripts/leave_open_no_activity.py

[leave_open_no_activity] Do not nag more than one time

---

auto_nag/scripts/needinfo_regression_author.py

[needinfo_regression_author] Ask only employees to set the severity

---

auto_nag/user_activity.py

[user_activity] Consider the user's activities on Phabricator

---

auto_nag/__init__.py

Log uncaught exceptions

---

.github/workflows/wiki.yaml
check_tools_on_wiki.py

This will allow the tool to run without the need to install dependencies.

[wiki] Remove the dependencies

---

auto_nag/scripts/configs/team_managers.json

Update manager of the Privacy Engineering team

---

.pre-commit-config.yaml

Update `isort` hook to 5.11.5

---

auto_nag/scripts/variant_expiration.py

[variant_expiration] Fix a typo

---

auto_nag/scripts/variant_expiration.py

[variant_expiration] Log error details when failing to create a bug

---

auto_nag/scripts/variant_expiration.py

[variant_expiration] Avoid using the default version value when creating a bug

---

auto_nag/multi_autofixers.py
auto_nag/scripts/multifix_regression.py

[multifix_regression] Fix the merging when having only two tools only

---

auto_nag/scripts/workflow/no_severity.py

[no_severity] Disable for bugs imported by Move to Bugzilla add-on

---

auto_nag/scripts/duplicate_copy_metadata.py
auto_nag/tests/test_webcompat_priority.py
auto_nag/webcompat_priority.py

[duplicate_copy_metadata] Copy WebCompat Priority flag

---

auto_nag/multi_autofixers.py
auto_nag/scripts/multifix_regression.py

[multifix_regression] Handle cases where the merge have one tool only

---

auto_nag/scripts/assignee_no_login.py

[assignee_no_login] Add a missed field in the bug handler

---

auto_nag/next_release.py
auto_nag/scripts/code_freeze_week.py
auto_nag/scripts/workflow/p2_merge_day.py
auto_nag/utils.py

Refactor to use Firefox Trains API instad of the wiki page

---

auto_nag/scripts/uplift_beta.py

Suggest uplifting to Beta even when Beta's status flag is `fix-optional`

---

auto_nag/next_release.py

[next_release] Don't nag on the release day

---

requirements.txt

In this way, dependabot will start updating the requests package. 
As a side effect, this could fix #1932.

Pin the requests package to the latest version

---

.github/workflows/add_to_project.yaml

Create a workflow to add new issues to the team project

---

auto_nag/scripts/moved_to_performance.py

[moved_to_performance] Fix the query to avoid commenting more than once

---

auto_nag/scripts/tracked_attention.py

[tracked_attention] Do not crash in the code freeze period

---

templates/fuzz_blockers_needinfo.txt

[fuzz_blockers] Reword the severity increase comment

---

auto_nag/round_robin.py
auto_nag/scripts/triage_rotations_outdated.py
auto_nag/tests/test_round_robin.py
auto_nag/utils.py
requirements.txt

Use a service account to access the rotation definitions spreadsheet

---

auto_nag/scripts/uplift_beta.py

This is a temporary workaround to avoid adding more noise. We should revert these changes once #1953 is fixed.

[uplift_beta] Workaround to exclude bugs with patches submitted through the new uplift workflow

---

.taskcluster.yml

Change `relman-auto-nag` to `bugbot` in Taskcluster configs

---

.taskcluster.yml

Specify the directory to avoid failing when cloning a fork with a different name

---

README.rst

Resolves #1853 and resolves #2018

Update the readme file

---

.github/pull_request_template.md
README.rst
bugbot/bzcleaner.py
bugbot/config.py
bugbot/log.py
bugbot/mail.py
bugbot/rules/assignee_no_login.py
bugbot/rules/crash_small_volume.py
bugbot/rules/inactive_ni_pending.py
bugbot/rules/inactive_reviewer.py
bugbot/rules/needinfo_regression_author.py
bugbot/rules/patch_closed_bug.py
bugbot/rules/topcrash_highlight.py
bugbot/rules/tracked_needinfo.py
bugbot/rules/uplift_beta.py
bugbot/rules/workflow/no_severity.py
bugbot/utils.py
scripts/cron_run_weekdays.sh
templates/common.html
tests/test_bzcleaner.py
tests/test_duplicate_copy_metadata.py

Update the bot's name and point to the new addresses

---

.github/mergify.yml

Currently, the body of the commit message contains HTML content from the PR body (e.g., https://github.com/mozilla/bugbot/commit/a51a03d85423ccb4a6a31b2179a9e188021a2ecf). With this PR, the commit message will have a title with an empty body.

ci(Mergify): Clean up the merge commit message

---

bugbot/rules/needinfo_regression_author.py

[needinfo_regression_author] Don't needinfo when the needinfo is blocked

---

bugbot/rules/close_intermittents.py
configs/rules.json

Otherwise we will catch up too slowly.

Close more intermittent bugs more frequently

---

bugbot/rules/multifix_regression.py
bugbot/rules/needinfo_regression_author.py

Avoid leaking regressing bug number if it's private

---

bugbot/rules/needinfo_regression_author.py

[needinfo_regression_author] Fix the `set_needinfo` method

---

bugbot/rules/regression_set_status_flags.py

[regression_set_status_flags] Replace the assertion with an error log

---

bugbot/rules/needinfo_regression_author.py

[needinfo_regression_author] Always set the comments' `is_private` filed

---

.taskcluster.yml

>**Note**: checking each commit  separately will show clear diffs
Fixes #1965

Restrict the events that will trigger Taskcluster

---

bugbot/rules/inactive_reviewer.py

[inactive_reviewer] Ignore patches where the filename is not matching phab-bot pattern

---

bugbot/rules/workflow/no_severity.py

[no_severity] Drop constraint on very old bugs

---

bugbot/rules/severity_inconsistency.py
templates/severity_inconsistency.html

Follow up on #2070 to resolve #2069.

[severity_inconsistency] Drop the dependency on the whiteboard tags

---

bugbot/rules/uplift_beta.py

[uplift_beta] Support GitHub pull requests

---

bugbot/rules/workflow/no_severity.py

s/Severty/Severity/ in nag_preamble() text

Fix typo in no_severity.py

---

bugbot/rules/close_intermittents.py
configs/rules.json
templates/close_intermittents.html

[close_intermittents] Add the Release Engineering product

---

bugbot/rules/workflow/no_severity.py

This reverts commit f80bb6ba5f197e9bed9948777eeb266a212a69d5.

[no_severity] Re-add the constraint on very old bugs

---

bugbot/rules/workflow/no_severity.py

Resolves #1889
This reverts commit d86f8a9a1a4aa5be3edb82892974e4b3d227b5eb.

[no_severity] Re-enable for bugs imported by Move to Bugzilla add-on

---

bugbot/rules/uplift_beta.py

This reverts commit c66a211780e46617217ad90f24eb849e693f5379 (Pull request #2011). See https://github.com/mozilla/bugbot/issues/1953#issuecomment-1563277998.

[uplift_beta] Revert a workaround to handle the new uplift workflow

---

scripts/cron_run_weekdays.sh

This reverts commit 500f20340ba5d9284be4997e05b258f36e6c2766 (Pull request #2010).

[patch_closed_bug] Re-enable the rule

---

bugbot/user_activity.py
requirements-dev.txt
tests/test_user_activity.py

[user_activity] Use a fixed reference date in the tests

---

.pre-commit-config.yaml

Set the default Python version in pre-commit to 3.10

---

bugbot/bzcleaner.py

Set the logging level to `DEBUG` when running in dry-run mode

---

bugbot/config.py
bugbot/crash/analyzer.py
bugbot/crash/socorro_util.py
bugbot/rules/file_crash_bug.py
scripts/cron_run_hourly.sh
templates/file_crash_bug.html
templates/file_crash_bug_description.md.jinja

Add a new rule to automatically file bugs for new actionable crashes

---

bugbot/rules/not_landed.py

[not_landed] Do not notify about bugs with test reminders

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py
templates/file_crash_bug_description.md.jinja

Highlight crash address commonalities

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py

File potential security crashes as security bugs

---

bugbot/rules/file_crash_bug.py
bugbot/user_activity.py

[file_crash_bug] Check the user status before adding a needinfo

---

bugbot/crash/analyzer.py

[crash/analyzer] Don't fetch when there are no signatures

---

bugbot/crash/analyzer.py

[crash/analyzer] Improve debugging logs

---

bugbot/rules/reminder.py

[reminder] Support adding reminders at the time of filing the bug

---

bugbot/rules/reminder.py

[reminder] Use the user's nick instead of the full name in the needinfo

---

bugbot/crash/analyzer.py

Add more allocator poison values to the list of targeted addresses

---

bugbot/rules/inactive_ni_pending.py

This will prevent closing bugs that were filed as unconfirmed, then later somebody confirmed the bug (e.g., we were able to reproduce the bug).
Currently, the rule is trying to apply changes to 92 bugs. However, the total of eligible bugs if we ignore the per triage owner limits is 984 bugs.   
The following spreadsheet summarizes the result of the dry-run before and after applying this PR: https://docs.google.com/spreadsheets/d/1rRU8JAwaKKwgTiYL1NI7cS1XOgB8JF-2KMXZfVpplH8

[inactive_ni_pending] Don't close bugs whose status was confirmed

---

bugbot/rules/file_crash_bug.py

[file_crash_bug] Be tolerant of HTTP errors when filing bugs

---

bugbot/rules/file_crash_bug.py

With this, cases like https://github.com/mozilla/bugbot/issues/2149#issuecomment-1621943787 will be easier to detect.

[file_crash_bug] Show the error message when failing to file a bug

---

bugbot/rules/file_crash_bug.py

[file_crash_bug] Add the regression keyword when we know the regressor

---

bugbot/bug/analyzer.py
bugbot/rules/regression_set_status_flags.py
tests/test_bug_analyzer.py
tests/test_regression_set_status_flags.py

This PR addresses the first three tasks in #2152.

Create a standalone logic to determine version status flags

---

bugbot/bug/analyzer.py
bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py

> **Note**
> Commits in this PR can be reviewed as independent changes 
Resolves #2162

[file_crash_bug] Set version status flags based on regressors

---

bugbot/crash/analyzer.py

[file_crash_bug] Set the timeout for Bugzilla to match the configurations

---

bugbot/rules/file_crash_bug.py

[file_crash_bug] Don't check status flags when `regressed_by` is missed

---

bugbot/rules/has_str_no_range.py

[has_str_no_range] Limit the rule to detect bugs

---

configs/rules.json

Resolves #2092
The dry-run results do not show an indication of any unexpected actions.

Add the "Release Engineering" product to all rules

---

bugbot/bug/analyzer.py

[bug/analyzer] Fix the bug handler

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py
templates/file_crash_bug_description.md.jinja

Extend the time frame for the crash bug summary

---

bugbot/rules/uplift_beta.py

_From @dklawren on [Slack](https://mozilla.slack.com/archives/C04LGP7428J/p1689795564730209?thread_ts=1685038845.582539&cid=C04LGP7428J):_
> I have just deployed changes to add more logging to our code responsible for setting the approval flags for uplift revisions. Can you ping me when you see a new occurrence of the flag not being set when it was supposed to?
This PR should help spot new occurrences.

[uplift_beta] Alert about potential out-of-sync uplift flags

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py
templates/file_crash_bug_description.md.jinja

[file_crash_bug] Fix the template and re-generate bugs

---

bugbot/rules/assignee_no_login.py

[assignee_no_login] Don't crash when there is no triage owner

---

templates/file_crash_bug_description.md.jinja

[file_crash_bug] Hide "Is use after free crash" when its value is "No"

---

templates/uplift_beta_needinfo.txt

[uplift_beta] Add a missing space in the needinfo comment

---

bugbot/rules/topcrash_highlight.py

This may fix the problem in #2100

[topcrash_highlight] Don't run the rule when the versions are not consistent

---

bugbot/crash/analyzer.py

[crash/analyzer] Reduce the number of workers for bugzilla-dev

---

bugbot/rules/copy_duplicate_info.py
bugbot/rules/duplicate_copy_metadata.py

Don't copy metadata from private duplicate bugs to public bugs

---

bugbot/rules/copy_duplicate_info.py
templates/copy_duplicate_info.html

Drop code that has been disabled since more than 4 years ago (#433)

[copy_duplicate_info] Drop disabled code

---

bugbot/rules/reminder.py

I wanted to put this in today for sec-approving.

Add a reminder-landing option

---

bugbot/rules/inactive_ni_pending.py

[inactive_ni_pending] Clarifying the bug closing comment

---

.pre-commit-config.yaml
bugbot/auto_mock.py
bugbot/bug/analyzer.py
bugbot/bzcleaner.py
bugbot/config.py
bugbot/crash/analyzer.py
bugbot/history.py
bugbot/nag_me.py
bugbot/people.py
bugbot/round_robin.py
bugbot/round_robin_calendar.py
bugbot/rules/code_freeze_week.py
bugbot/rules/prod_comp_changed_with_priority.py
bugbot/user_activity.py
bugbot/utils.py
templates/aborted_preamble.html
templates/p1_no_assignee.html
templates/p2_no_activity.html
templates/to_triage.html
tests/test_duplicate_copy_metadata.py
tests/test_escalation.py
tests/test_round_robin.py
tests/test_topcrash.py

Similer to:
- https://github.com/mozilla/bugbug/commit/99af2b7ecd665b0f973081c6ea0463ba14506332
- https://github.com/mozilla/bugbug/commit/34e2f1f0e8d415054af61c0c8c006f5b6cc66bd7

Fix pre-commit

---

.taskcluster.yml

Similar to https://github.com/mozilla/code-coverage/pull/2112

Switch Taskcluster to use GitHub checks API

---

bugbot/rules/topcrash_highlight.py

[topcrash_highlight] Supply bug metadata even when not applying changes

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py
templates/file_crash_bug.html
templates/file_crash_bug_description.md.jinja

[file_crash_bug] File bugs on production

---

bugbot/crash/analyzer.py

[file_crash_bug] Avoid using corrupted stack when filing a bug where possible

---

bugbot/crash/analyzer.py
templates/file_crash_bug_description.md.jinja

Resolves #2185
@amccreight: Could you please take a look? This is based on a suggestion you previously provided.

[file_crash_bug] Show "Process type" instead of "Crash kind"

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py

Resolves #2186 
@amccreight: Could you please take a look? This is based on the suggestion you previously provided.

[file_crash_bug] Add an additional filter for insignificant crashes

---

bugbot/crash/analyzer.py

[file_crash_bug] Exclude possible bit flip crashes

---

bugbot/crash/analyzer.py
bugbot/rules/file_crash_bug.py

[file_crash_bug ] Fix setting the release status flags

---

bugbot/rules/file_crash_bug.py

[file_crash_bug] Ignore the volume filtering step for regression bugs

---

bugbot/crash/analyzer.py
templates/file_crash_bug_description.md.jinja

> **Note**
> It would be clearer to review each commit individually
Resolves #2265

Exclude patches dated before the first crash from being a potential regressor

---

bugbot/topcrash.py

[topcrash] Ignore signatures that start with "bad hardware"

---

bugbot/rules/lot_of_cc.py
bugbot/rules/lot_of_comments.py
bugbot/rules/lot_of_see_also.py
bugbot/rules/lot_of_votes.py
templates/lot_of_cc.html
templates/lot_of_comments.html
templates/lot_of_see_also.html
templates/lot_of_votes.html

[lot_of_*] Add product::components to the email templates

---

bugbot/rules/crash_small_volume.py
bugbot/rules/security_unhide_dups.py

Unified way of accessing security keywords

---

scripts/check_rules_on_wiki.py

Do not fail on missing wiki documentation for experimental rules

---

scripts/check_rules_on_wiki.py

Follow up to fix a bug in #2342

[wiki] Add the file extensions to the ignored rules

---

bugbot/rules/inactive_ni_pending.py

[inactive_ni_pending] Ask for severity only on defect bugs

---

bugbot/rules/variant_expiration.py

[variant_expiration] Update the path for the `variants.yml` file

---

bugbot/bzcleaner.py
configs/rules.json

[regression_set_status_flags] Exclude bugs from the Firefox for iOS product

---

configs/rules.json

With this, @joewalker will receive emails for all BugBot's actions, excluding the error notification emails.

Add Joe Walker to the email notifications receivers

---

bugbot/rules/component.py

[component] Ignore bugs that are not available for BugBug

---

scripts/cron_run_hourly.sh
scripts/cron_run_weekdays.sh

This is related to https://github.com/mozilla/bugbot/pull/2453

[webcompat_platform_without_keyword] Run the rule hourly

---

bugbot/rules/close_intermittents.py

Misc improvements for autoclosing of intermittents

---

.pre-commit-config.yaml

Otherwise it fails to run on systems without that version of Python installed.

Don't set a default Python version in pre-commit config

---

.pre-commit-config.yaml

Updated `taskcluster_yml` from v0.0.10 to v0.0.11

---

configs/rules.json

Issue #2548 - Disable some nags for some WebCompat components.

---

.github/workflows/wiki.yaml

Upgrade the Python version for the wiki workflow from 3.9 to 3.12

---

bugbot/rules/component.py

[component] Exclude bugs reported by update-bot

---

bugbot/rules/component.py
configs/rules.json

Rename "Fenix" to "Firefox for Android"

---

tests/rules/test_perfalert_resolved_regression.py

This PR adds a regression test for PR #2587.

Add test for perfalert resolved

---

templates/uplift_beta_needinfo.txt

Add documentation link to uplift beta needinfo

---

.github/workflows/wiki.yaml
scripts/check_rules_on_wiki.py

Add a secret header to wiki requests

---

bugbot/rules/webcompat_score.py

This allows easilly assessing the actual computed impact score for each webcompat bug, without either needing to install the extension or go to BigQuery/ReDash and look at an SQL query.

Add the computed webcompat score to the user story

---

bugbot/rules/web_platform_features.py

Don't add links to see-also that are already in url

---

bugbot/rules/close_intermittents.py

Don't close intermittent bugs that have recent classifications
